EVALUATE
VAR SelectedYears = VALUES(dCalendario[Ano])  -- Get the selected years from dCalendario
VAR TableResult =
    ADDCOLUMNS(
        V_PRPGP_DISCENTES_POS, 
        "Aluno Ativo", 
        VAR ano_ingresso = V_PRPGP_DISCENTES_POS[Ano ingresso]  -- Project start year
        VAR ano_saida = V_PRPGP_DISCENTES_POS[Ano saída corrigido]  -- Project end year
        VAR YearsInRange = FILTER(SelectedYears, ano_ingresso <= [Ano] && ano_saida >= [Ano])  
        -- Check overlap
        RETURN IF(COUNTROWS(YearsInRange) > 0, 1, 0)  -- Return 1 if active, 0 if not
    )
RETURN
    SELECTCOLUMNS(
        TableResult,
        "Ano Ingresso", V_PRPGP_DISCENTES_POS[Ano ingresso],
        "Ano Saída Corrigido", V_PRPGP_DISCENTES_POS[Ano saída corrigido],
        "Aluno Ativo", [Aluno Ativo]
    )
