table PM_PROJETOS_PARTICIPANTES
	lineageTag: 950b6f7d-ac16-480e-8d4f-f2b182be4411

	measure 'Ano participação dentro do intervalo' = ```
			
			VAR YearToCheck = SELECTEDVALUE(dCalendario[Ano])  -- Get the year from the Calendar table
			VAR StartYear = YEAR(MIN([Data início participação]))  -- Get the year of the start date
			VAR EndYear = YEAR(MAX([Data fim participação]))  -- Get the year of the end date
			RETURN 
			IF(
			    YearToCheck >= StartYear && YearToCheck <= EndYear, 
			    1, 
			    0
			)
			
			```
		formatString: 0
		lineageTag: 420f0c4f-44f2-451f-a883-6e8b2ef83ba2

	column ID_PROJETO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 03609f5b-6723-42f2-b576-2e9869142312
		summarizeBy: none
		sourceColumn: ID_PROJETO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_CURSO_ALUNO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f8659a22-8d5d-4439-a76a-5a1cf74a3fa8
		summarizeBy: none
		sourceColumn: ID_CURSO_ALUNO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_CONTRATO_RH
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aed58778-1b04-44ae-a0d4-2c2f089bdd7a
		summarizeBy: none
		sourceColumn: ID_CONTRATO_RH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data fim participação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b028f736-2d18-4ece-827c-eec0f853c1b1
		summarizeBy: none
		sourceColumn: Data fim participação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data início participação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e055cf4c-9108-4dd3-891a-593e3001920b
		summarizeBy: none
		sourceColumn: Data início participação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition PM_PROJETOS_PARTICIPANTES = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    PM_PROJETOS_PARTICIPANTES1 = BEE{[Name="PM_PROJETOS_PARTICIPANTES"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(PM_PROJETOS_PARTICIPANTES1,{{"DT_FINAL", "Data fim participação"}, {"DT_INICIAL", "Data início participação"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

