table V_PRPGP_DISCENTES_POS
	lineageTag: 68361baf-98db-4955-8b69-d6584362a50b

	measure 'Aluno ativo no intervalo' = ```
			
			    VAR SelectedYears = VALUES(dCalendario[Ano])  -- Get the selected years from dCalendario
			    VAR ano_ingresso = MIN(V_PRPGP_DISCENTES_POS[Ano ingresso])  -- Project start year
			    VAR ano_saida = MAX(V_PRPGP_DISCENTES_POS[Ano saída corrigido])  -- Project end year
			    VAR YearsInRange = FILTER(SelectedYears, ano_ingresso <= [Ano] && ano_saida >= [Ano])  
			    -- Check overlap
			    RETURN IF(COUNTROWS(YearsInRange) > 0, 1, 0)  -- Return 1 if there is any overlap, otherwise 0
			```
		formatString: 0
		lineageTag: 7f0eb5e0-b0d0-4c65-8457-8e96fa8fa25e

	column ID_CURSO_ALUNO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8fc61f1e-182f-4a49-9d96-c9bf45265f8b
		summarizeBy: none
		sourceColumn: ID_CURSO_ALUNO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Matrícula
		dataType: string
		lineageTag: 69e9d438-3452-4a42-aa72-6311088b2728
		summarizeBy: none
		sourceColumn: Matrícula

		annotation SummarizationSetBy = Automatic

	column 'Nome aluno'
		dataType: string
		lineageTag: a5f4b775-a258-4311-85c4-ab20c721b5a0
		summarizeBy: none
		sourceColumn: Nome aluno

		annotation SummarizationSetBy = Automatic

	column 'Ano ingresso'
		dataType: int64
		formatString: 0
		lineageTag: b3103874-35f6-4f66-a93c-b1b07371309e
		summarizeBy: none
		sourceColumn: Ano ingresso

		annotation SummarizationSetBy = User

	column 'Ano saída'
		dataType: int64
		formatString: 0
		lineageTag: 98457c3d-3952-4741-98ba-0192f19d354c
		summarizeBy: none
		sourceColumn: Ano saída

		annotation SummarizationSetBy = User

	column 'Forma saída'
		dataType: string
		lineageTag: 44d55b86-2e12-47ac-8d3f-8e56efa72293
		summarizeBy: none
		sourceColumn: Forma saída

		annotation SummarizationSetBy = Automatic

	column Nacionalidade
		dataType: string
		lineageTag: cadf0df1-88b0-4a21-8518-5edc582e972a
		summarizeBy: none
		sourceColumn: Nacionalidade

		annotation SummarizationSetBy = Automatic

	column ID_PESSOA
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 93999f68-6a8d-4dae-9dfc-722a8c083f7c
		summarizeBy: none
		sourceColumn: ID_PESSOA

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Código curso'
		dataType: string
		lineageTag: fa83afee-b09c-4fb9-9d85-5f4fce1e5408
		summarizeBy: none
		sourceColumn: Código curso

		annotation SummarizationSetBy = Automatic

	column ID_UNIDADE_SUP
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4c725edf-3523-4d22-a09e-11419f05acac
		summarizeBy: none
		sourceColumn: ID_UNIDADE_SUP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Modalidade curso'
		dataType: string
		lineageTag: 2dfa31c4-6e83-40ab-8546-55ceaec324a3
		summarizeBy: none
		sourceColumn: Modalidade curso

		annotation SummarizationSetBy = Automatic

	column 'Ano saída corrigido'
		dataType: double
		isHidden
		formatString: 0
		lineageTag: 817e5c22-c7d1-45cb-b5b2-481cac1fd80e
		summarizeBy: none
		sourceColumn: Ano saída corrigido

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Ano defesa'
		dataType: int64
		formatString: 0
		lineageTag: 9fef4d46-0418-4731-b5c3-f31a91248ffe
		summarizeBy: none
		sourceColumn: Ano defesa

		annotation SummarizationSetBy = User

	column 'Situação plano estudos'
		dataType: string
		lineageTag: 894936b9-1839-4040-a329-b58aeac9a69a
		summarizeBy: none
		sourceColumn: Situação plano estudos

		annotation SummarizationSetBy = Automatic

	column 'Situação defesa'
		dataType: string
		lineageTag: a31957a4-f51f-48a9-badc-36de137c90fe
		summarizeBy: none
		sourceColumn: Situação defesa

		annotation SummarizationSetBy = Automatic

	column 'Data defesa'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 19027145-4cfe-495c-a3e2-5e7606869c85
		summarizeBy: none
		sourceColumn: Data defesa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Gênero
		dataType: string
		lineageTag: dcc0bb8f-11b4-498d-86d8-c0b83eb4f095
		summarizeBy: none
		sourceColumn: Gênero

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 2dcceb43-9f56-460a-aae3-b71fb999ef90
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	partition V_PRPGP_DISCENTES_POS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_DISCENTES_POS1 = BEE{[Name="V_PRPGP_DISCENTES_POS"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(V_PRPGP_DISCENTES_POS1,{{"ANO_EVASAO", "Ano saída"}, {"ANO_INGRESSO", "Ano ingresso"}, {"FORMA_EVASAO", "Forma saída"}, {"MATRICULA", "Matrícula"},{"NACIONALIDADE", "Nacionalidade"}, {"NOME_ALUNO", "Nome aluno"}}),
				    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Data ingresso", each Date.From(Text.From([Ano ingresso], "pt-BR")), type date),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Date",{{"MODALIDADE_CURSO", "Modalidade curso"}, {"COD_CURSO", "Código curso"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"Data ingresso"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Ano saída corrigido", each if [Ano saída] is null then Date.Year(DateTime.LocalNow()) else [Ano saída]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Ano saída corrigido", type number}}),
				    #"Inserted Date1" = Table.AddColumn(#"Changed Type", "Data defesa", each Date.From(Text.From([ANO_DEFESA], "pt-BR")), type date),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Date1",{{"ANO_DEFESA", "Ano defesa"}, {"SITUACAO_PLANO", "Situação plano estudos"}, {"SITUACAO_DEFESA", "Situação defesa"}, {"GENERO", "Gênero"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

