table V_PRPGP_DISCENTES_FLUXO
	lineageTag: 8074a767-b605-475b-9a3c-4803970216f8

	column Matrícula
		dataType: string
		lineageTag: 6c5b043b-d80c-4ac6-bb43-15e19d294cc8
		summarizeBy: none
		sourceColumn: Matrícula

		annotation SummarizationSetBy = Automatic

	column 'Ano referência'
		dataType: int64
		formatString: 0
		lineageTag: 8a846529-fabc-482c-9d45-4d09d614dab9
		summarizeBy: none
		sourceColumn: Ano referência

		annotation SummarizationSetBy = User

	column ID_TIPO_SITUACAO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ff55ac69-2c4f-46f8-bb87-f119851fc720
		summarizeBy: none
		sourceColumn: ID_TIPO_SITUACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Data referência'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 39285e09-2146-4cbc-bfae-fbd628ff26f3
		summarizeBy: none
		sourceColumn: Data referência

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition V_PRPGP_DISCENTES_FLUXO = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_DISCENTES_FLUXO1 = BEE{[Name="V_PRPGP_DISCENTES_FLUXO"]}[Data],
				    #"Inserted Date" = Table.AddColumn(V_PRPGP_DISCENTES_FLUXO1, "Data referência", each Date.From(Text.From([ANO_REFERENCIA], "pt-BR")), type date),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"MATRICULA", "Matrícula"}, {"ANO_REFERENCIA", "Ano referência"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

