table V_PRPGP_DOCENTES_POS
	lineageTag: d25995bd-961f-45d0-91b9-8aea0f5164e2

	measure 'Docente vinculado dentro do intervalo' = ```
			
			    VAR SelectedYears = VALUES(dCalendario[Ano])  -- Get the selected years from dCalendario
			    VAR ProjectStartYear = MIN(V_PRPGP_DOCENTES_POS[Ano ingresso])  -- Project start year
			    VAR ProjectEndYear = MAX(V_PRPGP_DOCENTES_POS[Ano desligamento])  -- Project end year
			    VAR YearsInRange = FILTER(SelectedYears, [Ano] >= ProjectStartYear && [Ano] <= ProjectEndYear)  
			    -- Check overlap
			    RETURN IF(COUNTROWS(YearsInRange) > 0, 1, 0)  -- Return 1 if there is any overlap, otherwise 0
			```
		formatString: 0
		lineageTag: a506be39-f0e1-4e25-a783-c6a8bd006eaa

	column ID_CONTRATO_RH
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bc343852-689d-4e74-ac7a-5c392b2da020
		summarizeBy: none
		sourceColumn: ID_CONTRATO_RH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SIAPE
		dataType: int64
		formatString: 0
		lineageTag: 0229dd6c-d0aa-4a7a-8bd1-8b7fd0efc6fb
		summarizeBy: none
		sourceColumn: SIAPE

		annotation SummarizationSetBy = User

	column 'Nome docente'
		dataType: string
		lineageTag: 3e8d8289-a64e-410c-a26f-34c0fde8d157
		summarizeBy: none
		sourceColumn: Nome docente

		annotation SummarizationSetBy = Automatic

	column Gênero
		dataType: string
		lineageTag: 90f79339-a3f8-46fd-8a85-d2a7060c6bbf
		summarizeBy: none
		sourceColumn: Gênero

		annotation SummarizationSetBy = Automatic

	column Cargo
		dataType: string
		lineageTag: 6b63ca3d-6a5d-44ce-8e2e-b1b5f6a8ef50
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column 'Data admissão'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 93c3ad4e-e2bb-4098-9db6-4c621141a5c0
		summarizeBy: none
		sourceColumn: Data admissão

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data desligamento'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 4787d5f2-fecb-4e35-acb7-e672eb9e794e
		summarizeBy: none
		sourceColumn: Data desligamento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Nacionalidade
		dataType: string
		lineageTag: e7b8ec4c-597a-4506-bf00-ec3296d276bb
		summarizeBy: none
		sourceColumn: Nacionalidade

		annotation SummarizationSetBy = Automatic

	column 'Ano ingresso'
		dataType: int64
		formatString: 0
		lineageTag: 02623384-597b-4fde-9a8f-563bae68b246
		summarizeBy: none
		sourceColumn: Ano ingresso

		annotation SummarizationSetBy = User

	column 'Ano desligamento'
		dataType: int64
		formatString: 0
		lineageTag: 6d79eb06-8548-43d9-bd78-311e5ea25302
		summarizeBy: none
		sourceColumn: Ano desligamento

		annotation SummarizationSetBy = User

	column ID_PESSOA
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ecb75a6e-7f98-424d-8f93-a731447721f0
		summarizeBy: none
		sourceColumn: ID_PESSOA

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Titulação
		dataType: string
		lineageTag: 3e8bcd32-7e91-4e8c-a922-61cbdc6c5b37
		summarizeBy: none
		sourceColumn: Titulação

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 98b819bd-8845-4a9b-9c2b-ff2ad91b0f09
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	partition V_PRPGP_DOCENTES_POS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_DOCENTES_POS1 = BEE{[Name="V_PRPGP_DOCENTES_POS"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(V_PRPGP_DOCENTES_POS1,{{"DESCR_CARGO", "Cargo"}, {"DT_ADMISSAO_CARGO", "Data ingresso"}, {"DT_DESLIGAMENTO", "Data desligamento"}, {"NACIONALIDADE", "Nacionalidade"}, {"SEXO", "Gênero"}, {"NOME_FUNCIONARIO", "Nome"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Ano ingresso", each Date.Year([Data ingresso]), Int64.Type),
				    #"Inserted Year1" = Table.AddColumn(#"Inserted Year", "Ano desligamento", each Date.Year([Data desligamento]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Data ingresso", "Data admissão"}, {"Nome", "Nome docente"}, {"TITULACAO", "Titulação"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

