table V_PRPGP_SCIVAL_AUTORES_METRICAS
	lineageTag: 15eb4ce0-bf05-4d9f-ab26-18b9918c9d31

	column ID_CONTRATO_RH
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2e136a03-533a-4fd5-ac7f-8ae4e7f83bbd
		summarizeBy: none
		sourceColumn: ID_CONTRATO_RH

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'ID Scopus'
		dataType: string
		lineageTag: 51325042-2b58-4694-bb1a-7119f9ebd469
		summarizeBy: none
		sourceColumn: ID Scopus

		annotation SummarizationSetBy = Automatic

	column 'Nome Scopus'
		dataType: string
		lineageTag: 790cf527-dbe3-4c32-b5fc-c40d7ec2f2e2
		summarizeBy: none
		sourceColumn: Nome Scopus

		annotation SummarizationSetBy = Automatic

	column ID_METRICA
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5cdf5bc7-5864-4aa9-b297-7055d726e5e3
		summarizeBy: none
		sourceColumn: ID_METRICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Ano Métrica'
		dataType: int64
		formatString: 0
		lineageTag: 1d98e073-0c05-4668-a9eb-31403d71a7bd
		summarizeBy: none
		sourceColumn: Ano Métrica

		annotation SummarizationSetBy = User

	column 'Valor métrica'
		dataType: double
		lineageTag: 9b99774c-c312-4299-897a-9808c508ae42
		summarizeBy: none
		sourceColumn: Valor métrica

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data coleta métrica'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: ae306b6f-908f-49c7-be71-be889d4085b7
		summarizeBy: none
		sourceColumn: Data coleta métrica

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data métrica'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a1f2d030-fcd6-4eec-8a32-868df50b4bc6
		summarizeBy: none
		sourceColumn: Data métrica

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nome métrica'
		dataType: string
		lineageTag: 6a1879f1-54c4-438b-bbdb-60eba150e568
		summarizeBy: none
		sourceColumn: Nome métrica

		annotation SummarizationSetBy = Automatic

	partition V_PRPGP_SCIVAL_AUTORES_METRICAS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_SCIVAL_AUTORES_METRICAS1 = BEE{[Name="V_PRPGP_SCIVAL_AUTORES_METRICAS"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(V_PRPGP_SCIVAL_AUTORES_METRICAS1,{{"VALOR_METRICA", "Valor métrica"}, {"SCOPUS_NAME", "Nome Scopus"}, {"SCOPUS_ID", "ID Scopus"}, {"ANO_METRICA", "Ano Métrica"}, {"DATA_COLETA", "Data coleta métrica"}}),
				    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Data métrica", each Date.From(Text.From([Ano Métrica], "pt-BR")), type date),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Date",{{"NOME_METRICA", "Nome métrica"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

