table V_PRPGP_PROJETOS_POS
	lineageTag: 677f56a3-689a-42ce-9af8-a01945892b3e

	measure 'Ano projeto dentro do intervalo' = ```
			
			    VAR SelectedYears = VALUES(dCalendario[Ano])  -- Get the selected years from dCalendario
			    VAR ProjectStartYear = YEAR(MIN(V_PRPGP_PROJETOS_POS[Data início]))  -- Project start year
			    VAR ProjectEndYear = YEAR(MAX(V_PRPGP_PROJETOS_POS[Data fim]))  -- Project end year
			    VAR YearsInRange = FILTER(SelectedYears, [Ano] >= ProjectStartYear && [Ano] <= ProjectEndYear)  
			    -- Check overlap
			    RETURN IF(COUNTROWS(YearsInRange) > 0, 1, 0)  -- Return 1 if there is any overlap, otherwise 0
			```
		formatString: 0
		lineageTag: afeddb9c-c20c-4806-8e44-a983594e7030

	measure 'Programa participa do projeto' =
			COUNTROWS(
			    FILTER(
			        V_PRPGP_PROJETOS_POS_ORGAOS,
			        COUNTROWS(
			            RELATEDTABLE(V_PRPGP_PROGRAMAS_POS)
			        ) > 0
			    )
			)
		formatString: 0
		lineageTag: 6829761f-1da5-448b-9f2d-349281638959

	column ID_PROJETO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ab4d6cdf-94d3-43d2-95e7-eed770e68f31
		summarizeBy: none
		sourceColumn: ID_PROJETO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Número processo'
		dataType: string
		lineageTag: 4b6ef86c-0379-4d73-bbbb-728677061193
		summarizeBy: none
		sourceColumn: Número processo

		annotation SummarizationSetBy = Automatic

	column Título
		dataType: string
		lineageTag: 73dc54c1-fb37-41e9-9dca-914d5285b4c8
		summarizeBy: none
		sourceColumn: Título

		annotation SummarizationSetBy = Automatic

	column 'Classificação projeto'
		dataType: string
		lineageTag: e3a65ce7-c925-406a-8d84-82d5bfe73f1a
		summarizeBy: none
		sourceColumn: Classificação projeto

		annotation SummarizationSetBy = Automatic

	column Situação
		dataType: string
		lineageTag: 7b391e1e-b0af-4d46-80d0-b3fbe8320417
		summarizeBy: none
		sourceColumn: Situação

		annotation SummarizationSetBy = Automatic

	column 'Data início'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 83776a89-c68d-46f0-beb8-87f707faf7c1
		summarizeBy: none
		sourceColumn: Data início

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Data fim'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 60769411-8234-4a76-a5c8-2fee20147a57
		summarizeBy: none
		sourceColumn: Data fim

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ano início'
		dataType: int64
		formatString: 0
		lineageTag: 8f52000d-5a76-4cb8-84b4-e739ad34a507
		summarizeBy: none
		sourceColumn: Ano início

		annotation SummarizationSetBy = User

	column 'Ano fim'
		dataType: int64
		formatString: 0
		lineageTag: 5cb8ee00-439e-4894-8fd4-e62ec60d633d
		summarizeBy: none
		sourceColumn: Ano fim

		annotation SummarizationSetBy = User

	partition V_PRPGP_PROJETOS_POS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_PROJETOS_POS1 = BEE{[Name="V_PRPGP_PROJETOS_POS"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(V_PRPGP_PROJETOS_POS1,{{"CLASSIFICACAO", "Classificação projeto"}, {"DT_INICIAL", "Data início"}, {"DT_CONCLUSAO", "Data fim"}, {"NUM_PROCESSO", "Número processo"}, {"SITUACAO", "Situação"}, {"TITULO", "Título"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Ano início", each Date.Year([Data início]), Int64.Type),
				    #"Inserted Year1" = Table.AddColumn(#"Inserted Year", "Ano fim", each Date.Year([Data fim]), Int64.Type)
				in
				    #"Inserted Year1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

