table V_PRPGP_ENCARGO_DIDATICO_POS
	lineageTag: 09ce9bdf-531d-41c7-9f5e-7828f8951882

	column 'Ano encargos'
		dataType: int64
		formatString: 0
		lineageTag: 72216b6a-3428-4d7e-84b1-6c0508440b96
		summarizeBy: none
		sourceColumn: Ano encargos

		annotation SummarizationSetBy = User

	column 'Soma encargo didático ano'
		dataType: double
		lineageTag: 785cc7a5-5d67-4923-bc31-56d2bda84d33
		summarizeBy: none
		sourceColumn: Soma encargo didático ano

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data encargo'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a2b513dd-fc1d-400f-8318-ed212900bb50
		summarizeBy: none
		sourceColumn: Data encargo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID_CONTRATO_RH
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bbdbea74-4e1d-48b0-ae36-b2e55eb46efc
		summarizeBy: none
		sourceColumn: ID_CONTRATO_RH

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition V_PRPGP_ENCARGO_DIDATICO_POS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_ENCARGO_DIDATICO_POS1 = BEE{[Name="V_PRPGP_ENCARGO_DIDATICO_POS"]}[Data],
				    #"Inserted Date" = Table.AddColumn(V_PRPGP_ENCARGO_DIDATICO_POS1, "Data encargo", each Date.From(Text.From([ANO_TURMA], "pt-BR")), type date),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"ANO_TURMA", "Ano encargos"}, {"ENCARGO_DIDATICO_DOCENTE", "Soma encargo didático ano"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

