{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"V_PRPGP_DISCENTES_POS\",\"V_PRPGP_DOCENTES_POS\",\"V_PRPGP_MEMBROS_BANCA\",\"Medidas\",\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\",\"SCIVAL_METRICAS\",\"V_PRPGP_PROGRAMAS_POS\",\"V_PRPGP_ENCARGO_DIDATICO_POS\",\"V_PRPGP_DISCENTES_FLUXO\",\"V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Spreadsheets"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_d9a4c154-801f-465f-9e19-a99850cd16b0",
        "fromColumn": "ID_UNIDADE_SUP",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "ID_UNIDADE_SUP",
        "toTable": "V_PRPGP_PROGRAMAS_POS"
      },
      {
        "name": "4d01a716-7ecb-fc01-4e37-347370733837",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "9aa63a5f-2607-e582-7a92-3cb937ccdbb0",
        "fromColumn": "Data ingresso",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "8c84a495-26e4-ce3b-d7a2-0058c04fc781",
        "fromColumn": "Data",
        "fromTable": "V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "095b32c3-fe8f-a667-88f3-b152b8c823c3",
        "fromColumn": "ID_UNIDADE_SUP",
        "fromTable": "V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO",
        "toColumn": "ID_UNIDADE_SUP",
        "toTable": "V_PRPGP_PROGRAMAS_POS"
      },
      {
        "name": "b65e81d5-c4a9-627a-c6b0-751b97850293",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "e993e7da-20f8-4a4f-eea8-d800c554e9fa",
        "fromColumn": "Data encargo",
        "fromTable": "V_PRPGP_ENCARGO_DIDATICO_POS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "fee1b589-38cc-7161-8727-afe1f47ba179",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "V_PRPGP_ENCARGO_DIDATICO_POS",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "715aae5a-634e-4fe0-e5dc-1df0c92ea08e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_DISCENTES_FLUXO",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "c9b53c5a-1041-256c-5376-3f5897bd6423",
        "fromColumn": "ID_UNIDADE_SUP",
        "fromTable": "V_PRPGP_DISCENTES_FLUXO",
        "toColumn": "ID_UNIDADE_SUP",
        "toTable": "V_PRPGP_PROGRAMAS_POS"
      },
      {
        "name": "664c694e-73aa-d616-495c-5d404c66b13a",
        "fromColumn": "Data",
        "fromTable": "V_PRPGP_DISCENTES_FLUXO",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "063df5d7-790a-6b54-6302-dea62138034e",
        "fromColumn": "ID_ORIENTADOR",
        "fromTable": "V_PRPGP_DISCENTES_POS",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "V_PRPGP_DISCENTES_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8fc61f1e-182f-4a49-9d96-c9bf45265f8b",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "Matrícula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e9d438-3452-4a42-aa72-6311088b2728",
            "sourceColumn": "Matrícula",
            "summarizeBy": "none"
          },
          {
            "name": "Nome aluno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f4b775-a258-4311-85c4-ab20c721b5a0",
            "sourceColumn": "Nome aluno",
            "summarizeBy": "none"
          },
          {
            "name": "Ano ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3103874-35f6-4f66-a93c-b1b07371309e",
            "sourceColumn": "Ano ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano saída",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98457c3d-3952-4741-98ba-0192f19d354c",
            "sourceColumn": "Ano saída",
            "summarizeBy": "none"
          },
          {
            "name": "Forma saída",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d55b86-2e12-47ac-8d3f-8e56efa72293",
            "sourceColumn": "Forma saída",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PESSOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "93999f68-6a8d-4dae-9dfc-722a8c083f7c",
            "sourceColumn": "ID_PESSOA",
            "summarizeBy": "none"
          },
          {
            "name": "Código curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa83afee-b09c-4fb9-9d85-5f4fce1e5408",
            "sourceColumn": "Código curso",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE_SUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c725edf-3523-4d22-a09e-11419f05acac",
            "sourceColumn": "ID_UNIDADE_SUP",
            "summarizeBy": "none"
          },
          {
            "name": "Modalidade curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dfa31c4-6e83-40ab-8546-55ceaec324a3",
            "sourceColumn": "Modalidade curso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano saída corrigido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "817e5c22-c7d1-45cb-b5b2-481cac1fd80e",
            "sourceColumn": "Ano saída corrigido",
            "summarizeBy": "none"
          },
          {
            "name": "Gênero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcc0bb8f-11b4-498d-86d8-c0b83eb4f095",
            "sourceColumn": "Gênero",
            "summarizeBy": "none"
          },
          {
            "name": "CPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dcceb43-9f56-460a-aae3-b71fb999ef90",
            "sourceColumn": "CPF",
            "summarizeBy": "none"
          },
          {
            "name": "ID_ORIENTADOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a3c144d8-7d92-4b1d-bb61-5af6bc076f93",
            "sourceColumn": "ID_ORIENTADOR",
            "summarizeBy": "none"
          },
          {
            "name": "NACIONALIDADE_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24318924-78a8-47e6-9300-63357431f4c6",
            "sourceColumn": "NACIONALIDADE_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "País de origem discente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b478d33-5b88-4b2e-a4ad-6cd46f8b45b1",
            "sourceColumn": "País de origem discente",
            "summarizeBy": "none"
          },
          {
            "name": "Origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "beaa86bb-5f5b-4759-b7cb-da15df33cfcd",
            "sourceColumn": "Origem",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68361baf-98db-4955-8b69-d6584362a50b",
        "measures": [
          {
            "name": "Aluno ativo no intervalo",
            "expression": [
              "",
              "    VAR SelectedYears = VALUES(dCalendario[Ano])  -- Get the selected years from dCalendario",
              "    VAR ano_ingresso = MIN(V_PRPGP_DISCENTES_POS[Ano ingresso])  -- Project start year",
              "    VAR ano_saida = MAX(V_PRPGP_DISCENTES_POS[Ano saída corrigido])  -- Project end year",
              "    VAR YearsInRange = FILTER(SelectedYears, ano_ingresso <= [Ano] && ano_saida >= [Ano])  ",
              "    -- Check overlap",
              "    RETURN IF(COUNTROWS(YearsInRange) > 0, 1, 0)  -- Return 1 if there is any overlap, otherwise 0"
            ],
            "formatString": "0",
            "lineageTag": "7f0eb5e0-b0d0-4c65-8457-8e96fa8fa25e"
          },
          {
            "name": "Discentes Ativos",
            "expression": "DISTINCTCOUNT(V_PRPGP_DISCENTES_FLUXO[ID_CURSO_ALUNO])",
            "formatString": "#,0",
            "lineageTag": "48e2e493-2d9b-4b1d-8edb-6eb551c0bdf3"
          },
          {
            "name": "Formados por ano de formatura",
            "expression": [
              "CALCULATE(",
              "    distinctcount(V_PRPGP_DISCENTES_POS[Matrícula]),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "b1c41e6d-28c5-4e68-b977-888b2137fd42"
          },
          {
            "name": "Doutorandos ativos",
            "expression": [
              "CALCULATE(",
              "     DISTINCTCOUNT(V_PRPGP_DISCENTES_FLUXO[ID_CURSO_ALUNO]),",
              "     V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Doutorado\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "b9a547bf-13ae-47b0-afe1-131615bc4896"
          },
          {
            "name": "Mestrandos ativos",
            "expression": [
              "CALCULATE(",
              "     DISTINCTCOUNT(V_PRPGP_DISCENTES_FLUXO[ID_CURSO_ALUNO]),",
              "     V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Mestrado\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "810caefd-2db3-44ba-bf56-1d6f4d610316"
          },
          {
            "name": "Pós-doutorandos ativos",
            "expression": [
              "CALCULATE(",
              "     DISTINCTCOUNT(V_PRPGP_DISCENTES_FLUXO[ID_CURSO_ALUNO]),",
              "     V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Pós-Doutorado\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b3177b2a-7a45-4bff-b1d7-0a826d50ec78"
          },
          {
            "name": "Tempo médio para formar (anos)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        V_PRPGP_DISCENTES_POS,",
              "        VAR AnoSaida = V_PRPGP_DISCENTES_POS[Ano saída]",
              "        VAR AnoIngresso =",
              "            CALCULATE(",
              "                MIN(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Data]),",
              "                REMOVEFILTERS(dCalendario)",
              "            )",
              "        RETURN",
              "            IF(",
              "                ISBLANK(AnoSaida) || ISBLANK(AnoIngresso),",
              "                BLANK(),",
              "                AnoSaida - AnoIngresso",
              "            )",
              "    ),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\"",
              ")"
            ],
            "lineageTag": "8a2a102f-f6fb-4647-a1b1-44293746b4fb"
          },
          {
            "name": "Tempo médio para formar mestres (anos)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        V_PRPGP_DISCENTES_POS,",
              "        VAR AnoSaida = V_PRPGP_DISCENTES_POS[Ano saída]",
              "        VAR AnoIngresso =",
              "            CALCULATE(",
              "                MIN(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Data]),",
              "                REMOVEFILTERS(dCalendario)",
              "            )",
              "        RETURN",
              "            IF(",
              "                ISBLANK(AnoSaida) || ISBLANK(AnoIngresso),",
              "                BLANK(),",
              "                AnoSaida - AnoIngresso",
              "            )",
              "    ),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\",",
              "    V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Mestrado\"",
              ")"
            ],
            "lineageTag": "427b8915-ceea-46f7-9200-7124dc49881e"
          },
          {
            "name": "Tempo médio para formar doutores (anos)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        V_PRPGP_DISCENTES_POS,",
              "        VAR AnoSaida = V_PRPGP_DISCENTES_POS[Ano saída]",
              "        VAR AnoIngresso =",
              "            CALCULATE(",
              "                MIN(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Data]),",
              "                REMOVEFILTERS(dCalendario)",
              "            )",
              "        RETURN",
              "            IF(",
              "                ISBLANK(AnoSaida) || ISBLANK(AnoIngresso),",
              "                BLANK(),",
              "                AnoSaida - AnoIngresso",
              "            )",
              "    ),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\",",
              "    V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Doutorado\"",
              ")"
            ],
            "lineageTag": "0c7860aa-6983-47af-8f0c-cccf54c667d7"
          },
          {
            "name": "Tempo médio para formar doutores (todos cursos)(anos)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        V_PRPGP_DISCENTES_POS,",
              "        VAR AnoSaida = V_PRPGP_DISCENTES_POS[Ano saída]",
              "        VAR AnoIngresso =",
              "            CALCULATE(",
              "                MIN(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Ano]),",
              "                ALL(V_PRPGP_DISCENTES_FLUXO[Data]),",
              "                REMOVEFILTERS(dCalendario)",
              "            )",
              "        RETURN",
              "            IF(",
              "                ISBLANK(AnoSaida) || ISBLANK(AnoIngresso),",
              "                BLANK(),",
              "                AnoSaida - AnoIngresso",
              "            )",
              "    ),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\",",
              "    V_PRPGP_DISCENTES_POS[Modalidade curso] = \"Doutorado\",",
              "    ALL(V_PRPGP_PROGRAMAS_POS[ID_UNIDADE_SUP])",
              ")"
            ],
            "lineageTag": "9117a2ab-e18a-4d8b-8824-54d0ef3bc970"
          },
          {
            "name": "Quantidade matriculados",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[Matrícula]),",
              "    ALL(dCalendario)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c42b2ac2-42d3-4524-ac65-6d1ca5045feb"
          },
          {
            "name": "Quantidade formados",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[Matrícula]),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\",",
              "    ALL(dCalendario)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "982b9f11-78df-478f-b197-cb625263d7cd"
          },
          {
            "name": "Taxa de Conclusão",
            "expression": [
              "",
              "DIVIDE([Quantidade formados], [Quantidade matriculados])"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d2f74a02-231c-4b6d-b9c4-0e3b9dc49fde"
          },
          {
            "name": "Brasileiro",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[ID_CURSO_ALUNO]),",
              "    V_PRPGP_DISCENTES_POS[País de origem discente] = \"Brasil\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ad6804cf-3d6e-4719-8dcb-89dd5cc4f158"
          }
        ],
        "partitions": [
          {
            "name": "V_PRPGP_DISCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCENTES_POS1 = BEE{[Name=\"V_PRPGP_DISCENTES_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DISCENTES_POS1,{{\"ANO_EVASAO\", \"Ano saída\"}, {\"ANO_INGRESSO\", \"Ano ingresso\"}, {\"FORMA_EVASAO\", \"Forma saída\"}, {\"MATRICULA\", \"Matrícula\"}, {\"NOME_ALUNO\", \"Nome aluno\"}, {\"NOME_PAIS_PORTUGUES\", \"País de origem\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Data ingresso\", each Date.From(Text.From([Ano ingresso], \"pt-BR\")), type date),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Date\",{{\"MODALIDADE_CURSO\", \"Modalidade curso\"}, {\"COD_CURSO\", \"Código curso\"}, {\"GENERO\", \"Gênero\"}",
                "}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"Data ingresso\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"Ano saída corrigido\", each if [Ano saída] is null then Date.Year(DateTime.LocalNow()) else [Ano saída]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Ano saída corrigido\", type number}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"F\",\"Feminino\",Replacer.ReplaceText,{\"Gênero\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"M\",\"Masculino\",Replacer.ReplaceText,{\"Gênero\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Replaced Value1\",{{\"País de origem\", \"País de origem discente\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns2\", \"Origem\", each if [NACIONALIDADE_ITEM] = 1 then \"Brasileiro\"",
                "else if [NACIONALIDADE_ITEM] <> null then \"estrangeiro\"",
                "else null)",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DOCENTES_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc343852-689d-4e74-ac7a-5c392b2da020",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "SIAPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0229dd6c-d0aa-4a7a-8bd1-8b7fd0efc6fb",
            "sourceColumn": "SIAPE",
            "summarizeBy": "none"
          },
          {
            "name": "Nome docente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8d8289-a64e-410c-a26f-34c0fde8d157",
            "sourceColumn": "Nome docente",
            "summarizeBy": "none"
          },
          {
            "name": "Data admissão",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "93c3ad4e-e2bb-4098-9db6-4c621141a5c0",
            "sourceColumn": "Data admissão",
            "summarizeBy": "none"
          },
          {
            "name": "Data desligamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4787d5f2-fecb-4e35-acb7-e672eb9e794e",
            "sourceColumn": "Data desligamento",
            "summarizeBy": "none"
          },
          {
            "name": "Ano ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02623384-597b-4fde-9a8f-563bae68b246",
            "sourceColumn": "Ano ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano desligamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d79eb06-8548-43d9-bd78-311e5ea25302",
            "sourceColumn": "Ano desligamento",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PESSOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ecb75a6e-7f98-424d-8f93-a731447721f0",
            "sourceColumn": "ID_PESSOA",
            "summarizeBy": "none"
          },
          {
            "name": "Titulação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8bcd32-7e91-4e8c-a922-61cbdc6c5b37",
            "sourceColumn": "Titulação",
            "summarizeBy": "none"
          },
          {
            "name": "CPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98b819bd-8845-4a9b-9c2b-ff2ad91b0f09",
            "sourceColumn": "CPF",
            "summarizeBy": "none"
          },
          {
            "name": "Gênero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a19974d-4a74-45e3-b227-16fa2d79da5f",
            "sourceColumn": "Gênero",
            "summarizeBy": "none"
          },
          {
            "name": "NACIONALIDADE_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "171bfa58-03de-4195-8710-cba77ada1aa1",
            "sourceColumn": "NACIONALIDADE_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "País de origem docente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "808bfcc2-d470-4a91-ba88-b33b9ec7dc70",
            "sourceColumn": "País de origem docente",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d25995bd-961f-45d0-91b9-8aea0f5164e2",
        "measures": [
          {
            "name": "Quantidade docentes permanentes",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Tipo de Vínculo] = \"Permanente\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "33c7c8fb-3c7d-4e6c-b151-b5c2333a5bcc"
          },
          {
            "name": "Tempo médio de permanência",
            "expression": [
              "",
              "AVERAGEX(",
              "    VALUES(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[ID_PESSOA]),",
              "    VAR AnoMin = ",
              "        CALCULATE(",
              "            MIN(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Data]),",
              "            REMOVEFILTERS(dCalendario)",
              "        )",
              "    VAR AnoMax = ",
              "        CALCULATE(",
              "            MAX(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Data]),",
              "            REMOVEFILTERS(dCalendario)",
              "        )",
              "    RETURN ",
              "        IF(",
              "            ISBLANK(AnoMin) || ISBLANK(AnoMax),",
              "            BLANK(),",
              "            AnoMax - AnoMin + 1",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5fa3a188-b1b9-45c5-9fe1-13b152d6f268"
          },
          {
            "name": "Anos vinculado ao programa",
            "expression": [
              "",
              "    VAR AnoReferencia = MAX(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano])",
              "    VAR AnoIngresso = CALCULATE(",
              "            MIN(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Ano]),",
              "            ALL(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Data]),",
              "            REMOVEFILTERS(dCalendario)",
              "        )",
              "    RETURN IF(",
              "            ISBLANK(AnoIngresso) || ISBLANK(AnoReferencia),",
              "            BLANK(),",
              "            AnoReferencia - AnoIngresso",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "255d6be7-59fd-40df-a78b-42732a60f571"
          },
          {
            "name": "Quantidade docentes colaboradores",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Tipo de Vínculo] = \"Colaborador\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0fd8570e-2303-471d-9037-04174e32ea6a"
          },
          {
            "name": "Quantidade docentes visitantes",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[Tipo de Vínculo] = \"Visitante\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "8442c448-9045-421f-b42e-0c0b6cc3b407"
          },
          {
            "name": "Professores vinculados 5+ anos",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    FILTER(",
              "        VALUES(V_PRPGP_DOCENTES_POS[CPF]),",
              "        NOT ISBLANK([Anos vinculado ao programa]) && [Anos vinculado ao programa] >= 5",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "cb0d5d6b-0305-4f63-9f49-42f16c8628db"
          },
          {
            "name": "Professores vinculados <5 anos",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    FILTER(",
              "        VALUES(V_PRPGP_DOCENTES_POS[CPF]),",
              "        NOT ISBLANK([Anos vinculado ao programa]) && [Anos vinculado ao programa] < 5",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "73d4b1f8-2e1c-4989-9414-d41a32028d11"
          },
          {
            "name": "Docentes brasileiros",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    V_PRPGP_DOCENTES_POS[País de origem docente] = \"Brasil\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "264d1863-3898-4b34-a85a-98b9cf05affb"
          },
          {
            "name": "Docentes estrangeiros",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DOCENTES_POS[CPF]),",
              "    V_PRPGP_DOCENTES_POS[País de origem docente] <> \"Brasil\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1b1ea0cc-c18f-4684-8643-83f3e174f489"
          },
          {
            "name": "Média orientandos por orientador",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[CPF]),",
              "        DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[ID_ORIENTADOR]",
              "    )",
              ")"
            ],
            "lineageTag": "2b0a72c3-3204-425c-a108-782cec5de77b"
          },
          {
            "name": "Média formados por orientador",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    DIVIDE(",
              "        DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[CPF]),",
              "        DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[ID_ORIENTADOR])",
              "    ),",
              "    V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\"",
              ")"
            ],
            "lineageTag": "815f0426-d455-44ee-b4f1-22edb958e535"
          },
          {
            "name": "Quantidade docentes",
            "expression": "DISTINCTCOUNT(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO[ID_CONTRATO_RH])",
            "formatString": "#,0",
            "lineageTag": "bccd83af-247c-40a2-886b-cfb69f285472"
          }
        ],
        "partitions": [
          {
            "name": "V_PRPGP_DOCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DOCENTES_POS1 = BEE{[Name=\"V_PRPGP_DOCENTES_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DOCENTES_POS1,{{\"DT_ADMISSAO_CARGO\", \"Data ingresso\"}, {\"DT_DESLIGAMENTO\", \"Data desligamento\"}, {\"GENERO\", \"Gênero\"}, {\"NOME_FUNCIONARIO\", \"Nome\"},{\"NOME_PAIS_PORTUGUES\", \"País de origem\"}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Renamed Columns\", \"Ano ingresso\", each Date.Year([Data ingresso]), Int64.Type),",
                "    #\"Inserted Year1\" = Table.AddColumn(#\"Inserted Year\", \"Ano desligamento\", each Date.Year([Data desligamento]), Int64.Type),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Year1\",{{\"Data ingresso\", \"Data admissão\"}, {\"Nome\", \"Nome docente\"}, {\"TITULACAO\", \"Titulação\"}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Renamed Columns1\",{{\"Nome docente\", Text.Proper, type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Capitalized Each Word\",{{\"País de origem\", \"País de origem docente\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_MEMBROS_BANCA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PLANO_ESTUDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "961548d3-a0c8-4721-90e3-509e39d70db4",
            "sourceColumn": "ID_PLANO_ESTUDO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PARTICIP_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "90890454-23c1-4ee0-a9c3-c9ee4d632da5",
            "sourceColumn": "ID_PARTICIP_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6529b173-77dc-434e-87a3-7d8011295df1",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo vínculo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5a8b9b-79fa-4f2d-ba5b-6672a0a1c8c7",
            "sourceColumn": "Tipo vínculo",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a09e5a2-7aa8-45af-8094-4ed6f5172ac9",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo participante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1cedcd9-0f37-4899-a1de-935edde69c81",
            "sourceColumn": "Tipo participante",
            "summarizeBy": "none"
          },
          {
            "name": "Nome participante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b008c72-e5b4-41c0-9850-87d90d51ccb2",
            "sourceColumn": "Nome participante",
            "summarizeBy": "none"
          },
          {
            "name": "Nome instituição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20b3a7a7-64e5-4d00-855a-4d0e5a16dbd9",
            "sourceColumn": "Nome instituição",
            "summarizeBy": "none"
          },
          {
            "name": "Sigla instituição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aec2c442-b603-43c1-8ab6-4ab79407d500",
            "sourceColumn": "Sigla instituição",
            "summarizeBy": "none"
          },
          {
            "name": "Titulação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bd59786-0ac5-40cf-b2fe-0a60721d6e3a",
            "sourceColumn": "Titulação",
            "summarizeBy": "none"
          },
          {
            "name": "CPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cc2249b-42e1-4114-a9e2-4dc568d4c5f5",
            "sourceColumn": "CPF",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec25bb49-2651-4236-afb6-3487ff330b24",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8250c80c-b9e1-44ac-a53b-6480f45db6e8",
        "partitions": [
          {
            "name": "V_PRPGP_MEMBROS_BANCA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_MEMBROS_BANCA1 = BEE{[Name=\"V_PRPGP_MEMBROS_BANCA\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_MEMBROS_BANCA1,{{\"SITUACAO\", \"Situação\"}, {\"TIPO_PARTICIPANTE\", \"Tipo participante\"}, {\"TIPO_VINCULO\", \"Tipo vínculo\"}, {\"NOME_INSTITUICAO\", \"Nome instituição\"}, {\"NOME_PARTICIPANTE\", \"Nome participante\"}, {\"SIGLA_INSTITUICAO\", \"Sigla instituição\"}, {\"TITULACAO\", \"Titulação\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "56645be1-c13c-46a5-9672-e762c3a9e0d3",
            "sourceColumn": "Column1",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "611794bc-dc79-429c-a42e-e7b76b4fb602",
        "measures": [
          {
            "name": "Vagas ofertadas",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Vagas ofertadas])",
            "formatString": "#,0",
            "lineageTag": "722ec88a-7913-47ba-8343-092b9a8546d7"
          },
          {
            "name": "Inscritos",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Inscritos])",
            "formatString": "#,0",
            "lineageTag": "93ab957e-fccc-43eb-8ac5-ac4ea7b2244b"
          },
          {
            "name": "Matriculados",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Matriculados])",
            "formatString": "#,0",
            "lineageTag": "9151ce3d-f36c-4b1d-a28e-de71f8d6bde5"
          },
          {
            "name": "Quantidade alunos",
            "expression": "DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[Matrícula])",
            "formatString": "0",
            "lineageTag": "29b81d79-61d2-4b67-acc9-7d3e05e2d1c4"
          },
          {
            "name": "Número orientandos",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[Matrícula]), ",
              "    V_PRPGP_MEMBROS_BANCA[Tipo participante] = \"Presidente\",",
              "    FILTER(",
              "        V_PRPGP_DISCENTES_POS, ",
              "        V_PRPGP_DISCENTES_POS[Ano saída] = SELECTEDVALUE(dCalendario[Ano])",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ce652f51-9eb0-4b23-8154-a9316427745b"
          },
          {
            "name": "Classificados",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Classificados])",
            "formatString": "#,0",
            "lineageTag": "4122d63c-460e-451e-af64-733555179e3a"
          },
          {
            "name": "HTML",
            "expression": [
              "\"<ul class='slides'>",
              "  <input type='radio' id='control-1' name='control' checked>",
              "  <input type='radio' id='control-2' name='control'>",
              "  <input type='radio' id='control-3' name='control'>",
              "  ",
              "  <!--  Left/Right Button  -->",
              "  <div class='navigator slide-1'>",
              "    <label for='control-3'>",
              "      <i class='fas fa-chevron-left'></i>",
              "    </label>",
              "    <label for='control-2'>",
              "      <i class='fas fa-chevron-right'></i>",
              "    </label>",
              "  </div>",
              "  ",
              "  <div class='navigator slide-2'>",
              "    <label for='control-1'>",
              "      <i class='fas fa-chevron-left'></i>",
              "    </label>",
              "    <label for='control-3'>",
              "      <i class='fas fa-chevron-right'></i>",
              "    </label>",
              "  </div>",
              "  ",
              "  <div class='navigator slide-3'>",
              "    <label for='control-2'>",
              "      <i class='fas fa-chevron-left'></i>",
              "    </label>",
              "    <label for='control-1'>",
              "      <i class='fas fa-chevron-right'></i>",
              "    </label>",
              "  </div>",
              "  <!--  /Left/Right Button  -->",
              "  ",
              "  <li class='slide'>1</li>",
              "  <li class='slide'>2</li>",
              "  <li class='slide'>3</li>",
              "  ",
              "  <div class='controls-visible'>",
              "    <label for='control-1'></label>",
              "    <label for='control-2'></label>",
              "    <label for='control-3'></label>",
              "  </div>",
              "</ul>",
              "<style> ",
              "body {",
              "  display: flex;",
              "  justify-content: center;",
              "  align-items: center;",
              "  min-height: 100vh;",
              "}",
              "",
              "ul.slides {",
              "  position: relative;",
              "  width: 600px;",
              "  height: 280px;",
              "  list-style: none;",
              "  margin: 0;",
              "  padding: 0;",
              "  background-color: #eee;",
              "  overflow: hidden;",
              "}",
              "",
              "li.slide {",
              "  margin: 0;",
              "  padding: 0;",
              "  width: inherit;",
              "  height: inherit;",
              "  position: absolute;",
              "  top: 0;",
              "  left: 0;",
              "  display: flex;",
              "  justify-content: center;",
              "  align-items: center;",
              "  font-family: Helvetica;",
              "  font-size: 120px;",
              "  color: #fff;",
              "  transition: .5s transform ease-in-out;",
              "}",
              "",
              ".slide:nth-of-type(1) {",
              "  background-color: #F2E205;",
              "}",
              "",
              ".slide:nth-of-type(2) {",
              "  background-color: #F25C05;",
              "  left: 100%;",
              "}",
              "",
              ".slide:nth-of-type(3) {",
              "  background-color: #495F8C;",
              "  left: 200%;",
              "}",
              "",
              "input[type='radio'] {",
              "  position: relative;",
              "  z-index: 100;",
              "  display: none;",
              "}",
              "",
              ".controls-visible {",
              "  position: absolute;",
              "  width: 100%;",
              "  bottom: 12px;",
              "  text-align: center;",
              "}",
              "",
              ".controls-visible label {",
              "  display: inline-block;",
              "  width: 10px;",
              "  height: 10px;",
              "  background-color: #fff;",
              "  border-radius: 50%;",
              "  margin: 0 3px;",
              "  border: 2px solid #fff;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(1):checked ~ .controls-visible label:nth-of-type(1) {",
              "  background-color: #333;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(2):checked ~ .controls-visible label:nth-of-type(2) {",
              "  background-color: #333;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(3):checked ~ .controls-visible label:nth-of-type(3) {",
              "  background-color: #333;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(1):checked ~ .slide {",
              "  transform: translatex(0%);",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(2):checked ~ .slide {",
              "  transform: translatex(-100%);",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(3):checked ~ .slide {",
              "  transform: translatex(-200%);",
              "}",
              "",
              "",
              "/* Left/Right Button Classes Below */",
              "",
              ".navigator {",
              "  position: absolute;",
              "  top: 50%;",
              "  transform: translatey(-50%);",
              "  width: 100%;",
              "  z-index: 100;",
              "  padding: 0 20px;",
              "  display: flex;",
              "  justify-content: space-between;",
              "  box-sizing: border-box;",
              "  display: none;",
              "}",
              "",
              ".navigator i {",
              "  font-size: 32px;",
              "  color #333;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(1):checked ~ .navigator:nth-of-type(1) {",
              "  display: flex;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(2):checked ~ .navigator:nth-of-type(2) {",
              "  display: flex;",
              "}",
              "",
              ".slides input[type='radio']:nth-of-type(3):checked ~ .navigator:nth-of-type(3) {",
              "  display: flex;",
              "}",
              "</style>\""
            ],
            "lineageTag": "6969c31d-1bb8-4d8e-b5ad-3e67a63bf3b0"
          },
          {
            "name": "Quantidade formados por ano de ingresso",
            "expression": [
              "",
              "VAR AnoSelecionado = SELECTEDVALUE(dCalendario[Ano])",
              "RETURN",
              "    CALCULATE(",
              "        DISTINCTCOUNT(V_PRPGP_DISCENTES_POS[Matrícula]),",
              "        V_PRPGP_DISCENTES_POS[Forma saída] = \"Formado\",",
              "        ALL(dCalendario),",
              "        IF(",
              "            NOT ISBLANK(AnoSelecionado),",
              "            V_PRPGP_DISCENTES_POS[Ano ingresso] = AnoSelecionado,",
              "            TRUE",
              "        )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "8f833692-d27a-4fea-9d08-57662318d61a"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "eaddaaa270234738bef92eb119e0c2d1"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "c25614ce-9cfb-44de-af38-bab886d2e0bc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fc7776aa-8758-4aa9-a356-94b23a408eb0",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1160af50-9af5-4aea-aec8-e2ed241d0a86",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "        min(V_PRPGP_DOCENTES_POS[Data admissão]), ",
                "        (TODAY())",
                "    ),",
                "    \"Ano\", YEAR([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb579bb5-cab1-4b11-a5d1-aaadd67b355b",
            "sourceColumn": "ID_CONCURSO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f3f9f0e7-85ac-423a-a80d-40983e92a6df",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "Cota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "199f04c7-6a01-4687-bc15-e65ba151d0a6",
            "sourceColumn": "Cota",
            "summarizeBy": "none"
          },
          {
            "name": "Vagas ofertadas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f5da43c-38f6-4fbc-8828-cec5621fbe53",
            "sourceColumn": "Vagas ofertadas",
            "summarizeBy": "none"
          },
          {
            "name": "Inscritos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc57a0af-4612-4ac1-8d9d-ee24333ada1e",
            "sourceColumn": "Inscritos",
            "summarizeBy": "none"
          },
          {
            "name": "Matriculados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eab32f34-7f4d-411e-8194-d6cd0c1773ca",
            "sourceColumn": "Matriculados",
            "summarizeBy": "none"
          },
          {
            "name": "Concurso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52d02086-1108-4c65-a993-a2d0c5cd45fe",
            "sourceColumn": "Concurso",
            "summarizeBy": "none"
          },
          {
            "name": "Edição concurso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48852ece-7cb3-4fdf-aa8e-b51b3db10bf7",
            "sourceColumn": "Edição concurso",
            "summarizeBy": "none"
          },
          {
            "name": "Curso vaga",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d6f0810-16da-474d-9318-3e8290e6166c",
            "sourceColumn": "Curso vaga",
            "summarizeBy": "none"
          },
          {
            "name": "Ano concurso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e46e826-010b-4d66-b55c-5287bceee5ef",
            "sourceColumn": "Ano concurso",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE_SUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "712c34c7-0062-4401-b241-1de6f8cf78ab",
            "sourceColumn": "ID_UNIDADE_SUP",
            "summarizeBy": "none"
          },
          {
            "name": "Concurso edital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29475326-65e2-40c5-99a9-f5b6c91ec561",
            "sourceColumn": "Concurso edital",
            "summarizeBy": "none"
          },
          {
            "name": "Ano ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74a94dcd-8568-49fc-a651-63fc263cb0d8",
            "sourceColumn": "Ano ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "Classificados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6cdb2b49-1ae5-4b3e-852d-d01561523218",
            "sourceColumn": "Classificados",
            "summarizeBy": "none"
          },
          {
            "name": "IND_INSCRICOES_CONCLUIDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "009c8c03-4940-4e43-87c9-0a28de30bacb",
            "sourceColumn": "IND_INSCRICOES_CONCLUIDAS",
            "summarizeBy": "none"
          },
          {
            "name": "Data ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2d9ad3b6-4703-4956-9cda-ccd64f0792e6",
            "sourceColumn": "Data ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "APTOS_LISTA_ESPERA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "46bbcf80-e125-436b-b8e4-6c7fd211624f",
            "sourceColumn": "APTOS_LISTA_ESPERA",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8bd13327-4213-43e5-962e-92172731b58a",
        "partitions": [
          {
            "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1 = BEE{[Name=\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\"]}[Data],",
                "    #\"Inserted Date\" = Table.AddColumn(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1, \"Data ingresso\", each Date.From(Text.From([ANO_INGRESSO], \"pt-BR\")), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Date\",{{\"ANO_CONCURSO\", \"Ano concurso\"}, {\"CANDIDATOS_INSCRITOS\", \"Inscritos\"}, {\"CANDIDATOS_MATRICULADOS\", \"Matriculados\"}, {\"DESCR_CONC_EDICAO\", \"Edição concurso\"}, {\"DESCR_CONCURSO\", \"Concurso\"}, {\"DESCR_COTA\", \"Cota\"}, {\"VAGAS_OFERECIDAS\", \"Vagas ofertadas\"}, {\"CURSO_VAGA\", \"Curso vaga\"}, {\"CANDIDATOS_CLASSIFICADOS\", \"Classificados\"}, {\"CONC_EDITAL\", \"Concurso edital\"}, {\"ANO_INGRESSO\", \"Ano ingresso\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"CANDIDATOS_CLASSIFICADOS_PCD\", \"CANDIDATOS_CLASSIFICADOS_PPI\", \"CANDIDATOS_INSCRITOS_PCD\", \"CANDIDATOS_INSCRITOS_PPI\", \"CANDIDATOS_MATRICULADOS_PCD\", \"CANDIDATOS_MATRICULADOS_PPI\", \"NOME_CURSO\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Ano ingresso] <> null and [Ano ingresso] <> 0))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SCIVAL_METRICAS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_METRICA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f66aeac-1d63-4869-a221-a426086957b2",
            "sourceColumn": "ID_METRICA",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome métrica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "258b8d69-e6c2-4f5a-bc45-fe4b1b5fa73b",
            "sourceColumn": "Nome métrica",
            "summarizeBy": "none"
          },
          {
            "name": "Nome métrica (Scival)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d5431f58-fc05-45c9-94a8-e6bf6be10483",
            "sourceColumn": "Nome métrica (Scival)",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf037958-bf20-49bd-bafa-dc290ffbefae",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b86b1f7-9c9a-4768-ac73-9b65e0577733",
        "partitions": [
          {
            "name": "SCIVAL_METRICAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    SCIVAL_METRICAS1 = BEE{[Name=\"SCIVAL_METRICAS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(SCIVAL_METRICAS1,{{\"NOME_SCIVAL\", \"Nome métrica (Scival)\"}, {\"METRICA\", \"Nome métrica\"}, {\"DESCRICAO\", \"Descrição\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_PROGRAMAS_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CENTRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "477ba964-4786-4568-a634-6d9009d32e34",
            "sourceColumn": "ID_CENTRO",
            "summarizeBy": "none"
          },
          {
            "name": "Nome centro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "347142ff-45a4-4609-a9a6-9635a7e84f1a",
            "sourceColumn": "Nome centro",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE_SUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4b3d46ca-ab81-40ed-aa3d-1513cafd7d0a",
            "sourceColumn": "ID_UNIDADE_SUP",
            "summarizeBy": "none"
          },
          {
            "name": "Nome unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deed6061-5ca4-4296-baa2-8ef3f2b33e84",
            "sourceColumn": "Nome unidade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c804e6fc-e8b7-4cd5-a570-f57eedc4184a",
        "partitions": [
          {
            "name": "V_PRPGP_PROGRAMAS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_PROGRAMAS_POS1 = BEE{[Name=\"V_PRPGP_PROGRAMAS_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_PROGRAMAS_POS1,{{\"NOME_UNIDADE_SUP\", \"Nome unidade\"}, {\"NOME_CENTRO\", \"Nome centro\"}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Nome unidade\", Text.Upper, type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Uppercased Text\",\"PROGRAMA DE PÓS-GRADUAÇÃO EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"PROGRAMA DE PÓS-GRADUAÇÃO MESTRADO PROFISSIONAL EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"CURSO-PROGRAMA PG-M EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"CURSO-PROGRAMA PG-D EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"CURSO-PROGRAMA PG PROFISSIONAL EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"CURSO-PROGRAMA PG EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"CURSO-PROGRAMA  PG EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"CURSO PG-MESTRADO PROFISSIONAL EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"CURSO PG-M \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"CURSO MESTRADO ACADÊMICO EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value9\",\"CURSO-PROGRAMA PG \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value13\",\"CURSO DE MESTRADO PROFISSIONAL EM \",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value10\",\" - Mestrado Profissional\",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value14\",\"- CAMPUS UFSM-FW\",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\" - UFSM-PM\",\"\",Replacer.ReplaceText,{\"Nome unidade\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Replaced Value12\",{{\"Nome unidade\", Text.Proper, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Capitalized Each Word\",{{\"Nome unidade\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_ENCARGO_DIDATICO_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data encargo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "a2b513dd-fc1d-400f-8318-ed212900bb50",
            "sourceColumn": "Data encargo",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bbdbea74-4e1d-48b0-ae36-b2e55eb46efc",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "Ano encargo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6da5b8c5-a768-4331-a06d-f280b606ffe8",
            "sourceColumn": "Ano encargo",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "902a948c-0062-40e7-8a6f-de4732bf1b27",
            "sourceColumn": "Semestre",
            "summarizeBy": "none"
          },
          {
            "name": "Encargo didático",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "11f7febd-3d57-468a-bf64-e7d7d1ca9c2b",
            "sourceColumn": "Encargo didático",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo encargo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ab799e-53d8-4511-b674-218dcdc2e710",
            "sourceColumn": "Tipo encargo",
            "summarizeBy": "none"
          },
          {
            "name": "Nível",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c20e457-5836-440a-accf-d4ec31229027",
            "sourceColumn": "Nível",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "09ce9bdf-531d-41c7-9f5e-7828f8951882",
        "measures": [
          {
            "name": "Soma Encargos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(V_PRPGP_ENCARGO_DIDATICO_POS[Encargo didático])",
            "lineageTag": "c3ab3b8d-e20d-466d-8d0f-afd3ee7da91a"
          }
        ],
        "partitions": [
          {
            "name": "V_PRPGP_ENCARGO_DIDATICO_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_ENCARGO_DIDATICO_POS1 = BEE{[Name=\"V_PRPGP_ENCARGO_DIDATICO_POS\"]}[Data],",
                "    #\"Inserted Date\" = Table.AddColumn(V_PRPGP_ENCARGO_DIDATICO_POS1, \"Data encargo\", each Date.From(Text.From([ANO], \"pt-BR\")), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Date\",{{\"ANO\", \"Ano encargo\"}, {\"ENCARGO\", \"Encargo didático\"}, {\"NIVEL_TIPO\", \"Nível\"}, {\"TIPO_ENCARGO\", \"Tipo encargo\"}, {\"PERIODO\", \"Semestre\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Semestre\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"1\",\"1º semestre\",Replacer.ReplaceText,{\"Semestre\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"2\",\"2º semestre\",Replacer.ReplaceText,{\"Semestre\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Encargo didático\", type number}}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Changed Type1\",\"GRADUAÇÃO\",\"Graduação\",Replacer.ReplaceText,{\"Nível\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"DOUTORADO\",\"Doutorado\",Replacer.ReplaceText,{\"Nível\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"MESTRADO\",\"Mestrado\",Replacer.ReplaceText,{\"Nível\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"OUTROS\",\"Outros\",Replacer.ReplaceText,{\"Nível\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"ESPECIALIZAÇÃO/RESIDENCIA\",\"Especialização/Residência\",Replacer.ReplaceText,{\"Nível\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Replaced Value6\",{\"ID_CONTRATO_RH\", \"Data encargo\", \"Ano encargo\", \"Semestre\", \"Nível\", \"Tipo encargo\", \"Encargo didático\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DISCENTES_FLUXO",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b51e0111-46bc-47b6-90b0-bb464754f559",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE_SUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "647605b7-ab2b-44cf-b141-e38b203fe09f",
            "sourceColumn": "ID_UNIDADE_SUP",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PESSOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a494503c-1529-407c-9afa-94fccc6372de",
            "sourceColumn": "ID_PESSOA",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e2e005a-241d-4548-ae84-1bfc8b3a9c73",
            "sourceColumn": "ANO",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO_INGRESSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7ad4d5a-c5a8-48e0-ba3c-cb7464ae8c5c",
            "sourceColumn": "ANO_INGRESSO",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO_EVASAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9c039b6-28f4-46b9-8aa1-021875fccb3f",
            "sourceColumn": "ANO_EVASAO",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "3c245bc4-8444-471f-be2b-78d435102053",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07ea08ac-17a7-48ee-af53-d34c88e4e80f",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "sum"
          },
          {
            "name": "CHAVE_UNICA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bb06696-21b2-4a17-ba54-a9fb7ff68de4",
            "sourceColumn": "CHAVE_UNICA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8074a767-b605-475b-9a3c-4803970216f8",
        "partitions": [
          {
            "name": "V_PRPGP_DISCENTES_FLUXO",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCENTES_FLUXO1 = BEE{[Name=\"V_PRPGP_DISCENTES_FLUXO\"]}[Data],",
                "    #\"Inserted Date\" = Table.AddColumn(V_PRPGP_DISCENTES_FLUXO1, \"Date\", each Date.From(Text.From([ANO], \"pt-BR\")), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Date\",{{\"Date\", \"Data\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1fb14ef-8b77-41a8-90bf-453de613a8f7",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE_SUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "af38dd88-519e-4222-bb62-750cd58f389f",
            "sourceColumn": "ID_UNIDADE_SUP",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PESSOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "45dc7560-67de-41fc-a16e-7a4244c19a20",
            "sourceColumn": "ID_PESSOA",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo de Vínculo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e99c832-45d2-470d-a142-d428c5428392",
            "sourceColumn": "Tipo de Vínculo",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32e45a4f-fa14-40f8-a375-cba0a3c3a6b8",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "07a29e69-040a-4803-961f-d71bafbee227",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "ANO_INICIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc69894e-3e91-4854-a318-af3c8daa6aec",
            "sourceColumn": "ANO_INICIAL",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO_FINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6d522336-2816-4b9c-bd80-b7f593311470",
            "sourceColumn": "ANO_FINAL",
            "summarizeBy": "sum"
          },
          {
            "name": "CHAVE_UNICA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8ae490a-680f-4a72-952b-216a1913a3fd",
            "sourceColumn": "CHAVE_UNICA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e0e41ed3-cfbf-4bb0-be75-974e4050791b",
        "partitions": [
          {
            "name": "V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO1 = BEE{[Name=\"V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO\"]}[Data],",
                "    #\"Inserted Date\" = Table.AddColumn(V_PRPGP_CREDENCIAMENTO_DOCENTE_FLUXO1, \"Data\", each Date.From(Text.From([ANO], \"pt-BR\")), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Date\",{{\"TIPO_VINCULO\", \"Tipo de Vínculo\"}, {\"ANO\", \"Ano\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}