table V_PRPGP_DISCENTES_FLUXO
	lineageTag: 8074a767-b605-475b-9a3c-4803970216f8

	column ID_CURSO_ALUNO
		dataType: int64
		formatString: 0
		lineageTag: b51e0111-46bc-47b6-90b0-bb464754f559
		summarizeBy: none
		sourceColumn: ID_CURSO_ALUNO

		annotation SummarizationSetBy = Automatic

	column ID_UNIDADE_SUP
		dataType: int64
		formatString: 0
		lineageTag: 647605b7-ab2b-44cf-b141-e38b203fe09f
		summarizeBy: none
		sourceColumn: ID_UNIDADE_SUP

		annotation SummarizationSetBy = Automatic

	column ID_PESSOA
		dataType: int64
		formatString: 0
		lineageTag: a494503c-1529-407c-9afa-94fccc6372de
		summarizeBy: sum
		sourceColumn: ID_PESSOA

		annotation SummarizationSetBy = Automatic

	column ANO
		dataType: int64
		formatString: 0
		lineageTag: 1e2e005a-241d-4548-ae84-1bfc8b3a9c73
		summarizeBy: sum
		sourceColumn: ANO

		annotation SummarizationSetBy = Automatic

	column ANO_INGRESSO
		dataType: int64
		formatString: 0
		lineageTag: c7ad4d5a-c5a8-48e0-ba3c-cb7464ae8c5c
		summarizeBy: sum
		sourceColumn: ANO_INGRESSO

		annotation SummarizationSetBy = Automatic

	column ANO_EVASAO
		dataType: int64
		formatString: 0
		lineageTag: d9c039b6-28f4-46b9-8aa1-021875fccb3f
		summarizeBy: sum
		sourceColumn: ANO_EVASAO

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3c245bc4-8444-471f-be2b-78d435102053
		summarizeBy: none
		sourceColumn: Data

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition V_PRPGP_DISCENTES_FLUXO = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_DISCENTES_FLUXO1 = BEE{[Name="V_PRPGP_DISCENTES_FLUXO"]}[Data],
				    #"Inserted Date" = Table.AddColumn(V_PRPGP_DISCENTES_FLUXO1, "Date", each Date.From(Text.From([ANO], "pt-BR")), type date),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"Date", "Data"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

