table V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS
	lineageTag: 8bd13327-4213-43e5-962e-92172731b58a

	column ID_CONCURSO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bb579bb5-cab1-4b11-a5d1-aaadd67b355b
		summarizeBy: none
		sourceColumn: ID_CONCURSO

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ID_CONC_EDICAO
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f3f9f0e7-85ac-423a-a80d-40983e92a6df
		summarizeBy: none
		sourceColumn: ID_CONC_EDICAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Cota
		dataType: string
		lineageTag: 199f04c7-6a01-4687-bc15-e65ba151d0a6
		summarizeBy: none
		sourceColumn: Cota

		annotation SummarizationSetBy = Automatic

	column 'Vagas ofertadas'
		dataType: int64
		formatString: 0
		lineageTag: 7f5da43c-38f6-4fbc-8828-cec5621fbe53
		summarizeBy: none
		sourceColumn: Vagas ofertadas

		annotation SummarizationSetBy = User

	column Inscritos
		dataType: int64
		formatString: 0
		lineageTag: cc57a0af-4612-4ac1-8d9d-ee24333ada1e
		summarizeBy: none
		sourceColumn: Inscritos

		annotation SummarizationSetBy = User

	column Matriculados
		dataType: int64
		formatString: 0
		lineageTag: eab32f34-7f4d-411e-8194-d6cd0c1773ca
		summarizeBy: none
		sourceColumn: Matriculados

		annotation SummarizationSetBy = User

	column Concurso
		dataType: string
		lineageTag: 52d02086-1108-4c65-a993-a2d0c5cd45fe
		summarizeBy: none
		sourceColumn: Concurso

		annotation SummarizationSetBy = Automatic

	column 'Edição concurso'
		dataType: string
		lineageTag: 48852ece-7cb3-4fdf-aa8e-b51b3db10bf7
		summarizeBy: none
		sourceColumn: Edição concurso

		annotation SummarizationSetBy = Automatic

	column 'Curso vaga'
		dataType: string
		lineageTag: 3d6f0810-16da-474d-9318-3e8290e6166c
		summarizeBy: none
		sourceColumn: Curso vaga

		annotation SummarizationSetBy = Automatic

	column 'Ano concurso'
		dataType: int64
		formatString: 0
		lineageTag: 1e46e826-010b-4d66-b55c-5287bceee5ef
		summarizeBy: none
		sourceColumn: Ano concurso

		annotation SummarizationSetBy = User

	column ID_UNIDADE_SUP
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 712c34c7-0062-4401-b241-1de6f8cf78ab
		summarizeBy: none
		sourceColumn: ID_UNIDADE_SUP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Concurso edital'
		dataType: string
		lineageTag: 29475326-65e2-40c5-99a9-f5b6c91ec561
		summarizeBy: none
		sourceColumn: Concurso edital

		annotation SummarizationSetBy = Automatic

	column 'Ano ingresso'
		dataType: int64
		formatString: 0
		lineageTag: 74a94dcd-8568-49fc-a651-63fc263cb0d8
		summarizeBy: none
		sourceColumn: Ano ingresso

		annotation SummarizationSetBy = User

	column Classificados
		dataType: int64
		formatString: 0
		lineageTag: 6cdb2b49-1ae5-4b3e-852d-d01561523218
		summarizeBy: none
		sourceColumn: Classificados

		annotation SummarizationSetBy = User

	column IND_INSCRICOES_CONCLUIDAS
		dataType: string
		isHidden
		lineageTag: 009c8c03-4940-4e43-87c9-0a28de30bacb
		summarizeBy: none
		sourceColumn: IND_INSCRICOES_CONCLUIDAS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data ingresso'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d9ad3b6-4703-4956-9cda-ccd64f0792e6
		summarizeBy: none
		sourceColumn: Data ingresso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column APTOS_LISTA_ESPERA
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 46bbcf80-e125-436b-b8e4-6c7fd211624f
		summarizeBy: sum
		sourceColumn: APTOS_LISTA_ESPERA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS = m
		mode: import
		source =
				let
				    Source = DB2.Database("bi.proj.ufsm.br", "bee", [HierarchicalNavigation=true, Implementation="Microsoft"]),
				    BEE = Source{[Schema="BEE"]}[Data],
				    V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1 = BEE{[Name="V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS"]}[Data],
				    #"Inserted Date" = Table.AddColumn(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1, "Data ingresso", each Date.From(Text.From([ANO_INGRESSO], "pt-BR")), type date),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"ANO_CONCURSO", "Ano concurso"}, {"CANDIDATOS_INSCRITOS", "Inscritos"}, {"CANDIDATOS_MATRICULADOS", "Matriculados"}, {"DESCR_CONC_EDICAO", "Edição concurso"}, {"DESCR_CONCURSO", "Concurso"}, {"DESCR_COTA", "Cota"}, {"VAGAS_OFERECIDAS", "Vagas ofertadas"}, {"CURSO_VAGA", "Curso vaga"}, {"CANDIDATOS_CLASSIFICADOS", "Classificados"}, {"CONC_EDITAL", "Concurso edital"}, {"ANO_INGRESSO", "Ano ingresso"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CANDIDATOS_CLASSIFICADOS_PCD", "CANDIDATOS_CLASSIFICADOS_PPI", "CANDIDATOS_INSCRITOS_PCD", "CANDIDATOS_INSCRITOS_PPI", "CANDIDATOS_MATRICULADOS_PCD", "CANDIDATOS_MATRICULADOS_PPI", "NOME_CURSO"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Ano ingresso] <> null and [Ano ingresso] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

