{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"V_PRPGP_CONCURSOS\",\"V_PRPGP_CURSOS_POS\",\"V_PRPGP_DEFESAS\",\"V_PRPGP_DISCENTES_POS\",\"V_PRPGP_DISCIPLINAS_POS\",\"V_PRPGP_DOCENTES_POS\",\"V_PRPGP_MEMBROS_BANCA\",\"V_PRPGP_MEMBROS_EXTERNOS_BANCAS\",\"V_PRPGP_PROJETOS_POS\",\"V_PRPGP_TIPOS_COTAS\",\"V_PRPGP_TURMAS_POS\",\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\",\"V_PRPGP_PROJETOS_POS_ORGAOS\",\"PM_PROJETOS_PARTICIPANTES\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9ae5ac53-ca79-4e7a-886b-5c9db1d6d9a8",
        "fromColumn": "DH_DEFESA",
        "fromTable": "V_PRPGP_DEFESAS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2ddb877-4123-4bfc-ae90-ba1f3167c4de"
      },
      {
        "name": "2ea7bf1a-3305-44e5-bb8a-9739326ad863",
        "fromColumn": "DT_ADMISSAO_CARGO",
        "fromTable": "V_PRPGP_DOCENTES_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f"
      },
      {
        "name": "dbe7e696-971d-40c9-8cc6-add71fc456d2",
        "fromColumn": "DT_DESLIGAMENTO",
        "fromTable": "V_PRPGP_DOCENTES_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35"
      },
      {
        "name": "947a2d1d-d9c4-4787-ace1-ebb94e0f1ea7",
        "fromColumn": "DT_INICIAL",
        "fromTable": "V_PRPGP_PROJETOS_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5cafaadf-62a2-46ac-964a-951db594eab0"
      },
      {
        "name": "37c5d120-397a-4c63-a24f-ef417392a3a3",
        "fromColumn": "DT_CONCLUSAO",
        "fromTable": "V_PRPGP_PROJETOS_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_33034433-a6c7-4857-919a-bebeb3fbb368"
      },
      {
        "name": "AutoDetected_7f6fa9d2-4534-42f4-84db-c21d22a200bb",
        "fromColumn": "ID_CONC_EDICAO",
        "fromTable": "V_PRPGP_TIPOS_COTAS",
        "toColumn": "ID_CONC_EDICAO",
        "toTable": "V_PRPGP_CONCURSOS"
      },
      {
        "name": "AutoDetected_bfce4d92-ad53-4272-b6e4-5d4b444aa162",
        "fromColumn": "ID_CONC_EDICAO",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "ID_CONC_EDICAO",
        "toTable": "V_PRPGP_CONCURSOS"
      },
      {
        "name": "AutoDetected_a6566ff1-61f4-490a-bb0a-06cb95fa56e1",
        "fromColumn": "ID_CURSO",
        "fromTable": "V_PRPGP_DISCENTES_POS",
        "toColumn": "ID_CURSO",
        "toTable": "V_PRPGP_CURSOS_POS"
      },
      {
        "name": "AutoDetected_56fd4ca3-519d-43de-b2c3-ecba9645d848",
        "fromColumn": "ID_CURSO",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "ID_CURSO",
        "toTable": "V_PRPGP_CURSOS_POS"
      },
      {
        "name": "AutoDetected_0baff941-8596-4cc6-8810-be3202bce726",
        "fromColumn": "ID_PLANO_ESTUDO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_PLANO_ESTUDO",
        "toTable": "V_PRPGP_DEFESAS"
      },
      {
        "name": "221f380e-7734-0d6e-9f3c-aa2cef1a255b",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "df979e70-c8a2-7d17-49ea-284dc310c56f",
        "fromColumn": "ID_DOCENTE",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "162a652d-abc0-4fc9-e606-dd76664f2925",
        "fromColumn": "ID_DISCIPLINA",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_DISCIPLINA",
        "toTable": "V_PRPGP_DISCIPLINAS_POS"
      },
      {
        "name": "02b80666-d49a-6b6e-1c45-66507b16dd7f",
        "fromColumn": "ID_PARTICIP_PLANO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_PARTICIP_PLANO",
        "toTable": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS"
      },
      {
        "name": "f8181591-1c9b-45aa-aabb-6e2312d6cb54",
        "fromColumn": "DT_FINAL",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_80b1c078-b91c-4491-a47d-6e8aca5ec8d5"
      },
      {
        "name": "68437775-5129-0fc8-a259-4ccdcac9f152",
        "fromColumn": "ID_PROJETO",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_PROJETO",
        "toTable": "V_PRPGP_PROJETOS_POS"
      },
      {
        "name": "2b3ef027-1396-c497-cc4c-c0f955097d55",
        "fromColumn": "ID_PROJETO",
        "fromTable": "V_PRPGP_PROJETOS_POS_ORGAOS",
        "toColumn": "ID_PROJETO",
        "toTable": "V_PRPGP_PROJETOS_POS"
      },
      {
        "name": "6da48ca3-16f6-232a-44e4-5752fadf7461",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "67551456-b0b8-61d5-4ead-1612acdf30ea",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "093b44da-e511-45a3-6c1e-2e00f1d4ee14",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "1112f5ab-f756-8bb5-c47d-69e03ad65564",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_53f11cfa-ca4c-4abc-9af5-9af882a32f14",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bbdc223c-d11c-450e-973b-dd31cb148ad3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ffd875bf-5b7b-415b-9a61-3bd0db6cdfa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3098504c-603f-4e1b-92da-93640009f742",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ecc9a347-5eec-46b2-9811-7e06f1dd28cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dc6e667d-cd34-47ed-811f-819ec616b634",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8475cfce-535b-4295-9ac1-e949d050e481",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8aa60150-d273-40ab-b4f9-98ad3865cc0c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "469cfe5d-d0f8-46ac-88a0-8cb0874ec051",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a0db6530-724b-46d9-af85-4b930e7741c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5508a7b4-a333-4cad-9ded-68f03fd353d5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f9b57742-e09c-45ef-bc02-52d01b038997",
                "ordinal": 3
              }
            ],
            "lineageTag": "3543001d-5bd1-4d55-92dc-5702a5063dd9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e2c5fa93-7bd9-44ef-aa93-afb2d2bb974d",
        "partitions": [
          {
            "name": "DateTableTemplate_53f11cfa-ca4c-4abc-9af5-9af882a32f14",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_CONCURSOS",
        "columns": [
          {
            "name": "ID_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9178df64-d416-45ea-9b8e-eb78c33eedf4",
            "sourceColumn": "ID_CONCURSO",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCR_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5317f253-d81f-4011-8d29-68884731e1b5",
            "sourceColumn": "DESCR_CONCURSO",
            "summarizeBy": "none"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ee9f0f0-71d1-4803-ae49-9fa5ba30332c",
            "sourceColumn": "ANO",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa84dec6-f13e-47b6-9d1a-058cc8847e93",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "DESCR_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afe4130c-be59-4473-8ca8-841bcae7d000",
            "sourceColumn": "DESCR_CONC_EDICAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b016d5a-46b3-48e5-a6a4-08c77803f102",
        "partitions": [
          {
            "name": "V_PRPGP_CONCURSOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_CONCURSOS1 = BEE{[Name=\"V_PRPGP_CONCURSOS\"]}[Data]",
                "in",
                "    V_PRPGP_CONCURSOS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_CURSOS_POS",
        "columns": [
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c212997-5966-4c49-9f0d-eb084fe16c81",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "COD_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5a56728-37d0-4645-82dd-83e8b9009c45",
            "sourceColumn": "COD_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a344cffe-1f4c-41f4-be48-ad27c3a13c45",
            "sourceColumn": "NOME_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "NIVEL_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "279c7aaf-10d2-46ec-b950-68261f807990",
            "sourceColumn": "NIVEL_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "MODALIDADE_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acbec8b8-ae81-464d-b67f-3acb54d7b93f",
            "sourceColumn": "MODALIDADE_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "CLASSIFICACAO_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80f3a514-e371-4d05-8abd-1d028365663a",
            "sourceColumn": "CLASSIFICACAO_CURSO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7f424f93-fe10-4152-8ee3-899949d932f9",
        "partitions": [
          {
            "name": "V_PRPGP_CURSOS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_CURSOS_POS1 = BEE{[Name=\"V_PRPGP_CURSOS_POS\"]}[Data]",
                "in",
                "    V_PRPGP_CURSOS_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DEFESAS",
        "columns": [
          {
            "name": "ID_PLANO_ESTUDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1abf5ad2-3dcb-4411-b416-aa78eebc295e",
            "sourceColumn": "ID_PLANO_ESTUDO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "585535c8-c66c-4a07-90a4-02511eb430fa",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "sum"
          },
          {
            "name": "DH_DEFESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a3cc67cb-804a-46e1-af44-17d1cea7e349",
            "sourceColumn": "DH_DEFESA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e2ddb877-4123-4bfc-ae90-ba1f3167c4de"
                },
                "isDefault": true,
                "relationship": "9ae5ac53-ca79-4e7a-886b-5c9db1d6d9a8"
              }
            ]
          },
          {
            "name": "SITUACAO_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e13cf5e-6716-4302-840f-3e901b031d3d",
            "sourceColumn": "SITUACAO_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "SITUACAO_DEFESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81a6c5bf-baf8-465d-a9b5-de6517e6c9d9",
            "sourceColumn": "SITUACAO_DEFESA",
            "summarizeBy": "none"
          },
          {
            "name": "Contagem de Defesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CALCULATE(COUNTROWS(V_PRPGP_DEFESAS), ALLEXCEPT(V_PRPGP_DEFESAS, V_PRPGP_DEFESAS[SITUACAO_DEFESA]))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9d275bf6-75b3-4d7e-a78e-4a483da381de",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "2f1fedb7-dace-478f-8610-18ad19029bda",
        "partitions": [
          {
            "name": "V_PRPGP_DEFESAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DEFESAS1 = BEE{[Name=\"V_PRPGP_DEFESAS\"]}[Data]",
                "in",
                "    V_PRPGP_DEFESAS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e2ddb877-4123-4bfc-ae90-ba1f3167c4de",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0d40c45a-ee34-4e9d-a5cc-a91d84256f1b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e0104963-db68-4d91-a642-b0a092dcaeff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9e8d1a60-e41c-4487-bb55-01ff90ed90c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "81ad7520-168f-47d8-8e18-c696a49d7cab",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "149c94be-aa10-43ff-accb-7682839e838f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b3135703-6084-4e37-9cf7-06fde4f9f8ff",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "271422fb-6212-4cc7-828f-5510099ab462",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8b78d755-7b30-4395-8264-dc066e2a5ae8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3045d0e2-8454-4429-9bd5-17253a4396cf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d6365c49-eca4-4756-955f-87161cb1e2ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "465eac91-cfac-4c93-ad3f-58bf8f7d5226",
                "ordinal": 3
              }
            ],
            "lineageTag": "2688e226-46dd-4015-b78c-c24f8e05c8e6"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a3d85a2-3ccc-4a48-874f-25f21f3ebb4c",
        "partitions": [
          {
            "name": "LocalDateTable_e2ddb877-4123-4bfc-ae90-ba1f3167c4de",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DEFESAS'[DH_DEFESA])), 1, 1), Date(Year(MAX('V_PRPGP_DEFESAS'[DH_DEFESA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "V_PRPGP_DISCENTES_POS",
        "columns": [
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8fc61f1e-182f-4a49-9d96-c9bf45265f8b",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "MATRICULA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e9d438-3452-4a42-aa72-6311088b2728",
            "sourceColumn": "MATRICULA",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f4b775-a258-4311-85c4-ab20c721b5a0",
            "sourceColumn": "NOME_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ANO_INGRESSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3103874-35f6-4f66-a93c-b1b07371309e",
            "sourceColumn": "ANO_INGRESSO",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO_EVASAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98457c3d-3952-4741-98ba-0192f19d354c",
            "sourceColumn": "ANO_EVASAO",
            "summarizeBy": "sum"
          },
          {
            "name": "FORMA_EVASAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d55b86-2e12-47ac-8d3f-8e56efa72293",
            "sourceColumn": "FORMA_EVASAO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e50fe787-0b41-4d4e-9e7d-cc1b35d057f7",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad5c1641-67ee-4a19-954a-1d55c755c2f0",
            "sourceColumn": "NOME_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "NIVEL_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ac3f5e1-8041-4e9c-8af4-97e4330dfcb9",
            "sourceColumn": "NIVEL_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "MODALIDADE_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bc2890c-f362-416e-b525-f75145445bf6",
            "sourceColumn": "MODALIDADE_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "NACIONALIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"V_PRPGP_DISCENTES_POS\",\"TableItemName\":\"NACIONALIDADE_AGRUPADA\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "cadf0df1-88b0-4a21-8518-5edc582e972a",
            "sourceColumn": "NACIONALIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "NACIONALIDADE_AGRUPADA",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"v\",\"Entity\":\"V_PRPGP_DISCENTES_POS\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"NACIONALIDADE\"}}],\"GroupItems\":[{\"DisplayName\":\"(Em branco)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Alemã(ão) & Angolano(a) & Argentino(a) & Boliviano(a) & ...\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"NACIONALIDADE\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Alemã(ão)'\"}}],[{\"Literal\":{\"Value\":\"'Angolano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Argentino(a)'\"}}],[{\"Literal\":{\"Value\":\"'Boliviano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Cabo-verdiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Camaronês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Chileno(a)'\"}}],[{\"Literal\":{\"Value\":\"'Colombiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Cubano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Equatoriano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Espanhol(a)'\"}}],[{\"Literal\":{\"Value\":\"'Ganês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Guatemalteco(a)'\"}}],[{\"Literal\":{\"Value\":\"'Guianês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Guineense'\"}}],[{\"Literal\":{\"Value\":\"'Haitiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Hondurenho(a)'\"}}],[{\"Literal\":{\"Value\":\"'Indiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Italiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Mexicano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Moçambicano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Nicaraguense'\"}}],[{\"Literal\":{\"Value\":\"'Nigeriano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Norte Americano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paquistanês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paraguaio(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paraguaio(a) Naturalizado(a)'\"}}],[{\"Literal\":{\"Value\":\"'Peruano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Português(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Salvadorenho(a)'\"}}],[{\"Literal\":{\"Value\":\"'São-tomense'\"}}],[{\"Literal\":{\"Value\":\"'Senegalês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Surinamês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Timorense'\"}}],[{\"Literal\":{\"Value\":\"'Tunisiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Uruguaio(a)'\"}}],[{\"Literal\":{\"Value\":\"'Uruguaio(a) Naturalizado(a)'\"}}],[{\"Literal\":{\"Value\":\"'Venezuelano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Venezuelano(a) Naturalizado(a)'\"}}]]}}},{\"DisplayName\":\"Brasileiro(a) & Brasileiro(a) Naturalizado(a)\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"NACIONALIDADE\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Brasileiro(a)'\"}}],[{\"Literal\":{\"Value\":\"'Brasileiro(a) Naturalizado(a)'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('V_PRPGP_DISCENTES_POS'[NACIONALIDADE]),",
              "\t\"(Em branco)\",",
              "\t'V_PRPGP_DISCENTES_POS'[NACIONALIDADE] IN {\"Alemã(ão)\",",
              "\t\t\"Angolano(a)\",",
              "\t\t\"Argentino(a)\",",
              "\t\t\"Boliviano(a)\",",
              "\t\t\"Cabo-verdiano(a)\",",
              "\t\t\"Camaronês(esa)\",",
              "\t\t\"Chileno(a)\",",
              "\t\t\"Colombiano(a)\",",
              "\t\t\"Cubano(a)\",",
              "\t\t\"Equatoriano(a)\",",
              "\t\t\"Espanhol(a)\",",
              "\t\t\"Ganês(a)\",",
              "\t\t\"Guatemalteco(a)\",",
              "\t\t\"Guianês(esa)\",",
              "\t\t\"Guineense\",",
              "\t\t\"Haitiano(a)\",",
              "\t\t\"Hondurenho(a)\",",
              "\t\t\"Indiano(a)\",",
              "\t\t\"Italiano(a)\",",
              "\t\t\"Mexicano(a)\",",
              "\t\t\"Moçambicano(a)\",",
              "\t\t\"Nicaraguense\",",
              "\t\t\"Nigeriano(a)\",",
              "\t\t\"Norte Americano(a)\",",
              "\t\t\"Paquistanês(a)\",",
              "\t\t\"Paraguaio(a)\",",
              "\t\t\"Paraguaio(a) Naturalizado(a)\",",
              "\t\t\"Peruano(a)\",",
              "\t\t\"Português(esa)\",",
              "\t\t\"Salvadorenho(a)\",",
              "\t\t\"São-tomense\",",
              "\t\t\"Senegalês(esa)\",",
              "\t\t\"Surinamês(a)\",",
              "\t\t\"Timorense\",",
              "\t\t\"Tunisiano(a)\",",
              "\t\t\"Uruguaio(a)\",",
              "\t\t\"Uruguaio(a) Naturalizado(a)\",",
              "\t\t\"Venezuelano(a)\",",
              "\t\t\"Venezuelano(a) Naturalizado(a)\"},",
              "\t\"Alemã(ão) & Angolano(a) & Argentino(a) & Boliviano(a) & ...\",",
              "\t'V_PRPGP_DISCENTES_POS'[NACIONALIDADE] IN {\"Brasileiro(a)\",",
              "\t\t\"Brasileiro(a) Naturalizado(a)\"},",
              "\t\"Brasileiro(a) & Brasileiro(a) Naturalizado(a)\",",
              "\t'V_PRPGP_DISCENTES_POS'[NACIONALIDADE]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "V_PRPGP_DISCENTES_POS"
                          }
                        },
                        "Property": "NACIONALIDADE"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ce12d12c-9ac8-4377-b60f-28ed6081b14c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "68361baf-98db-4955-8b69-d6584362a50b",
        "partitions": [
          {
            "name": "V_PRPGP_DISCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCENTES_POS1 = BEE{[Name=\"V_PRPGP_DISCENTES_POS\"]}[Data]",
                "in",
                "    V_PRPGP_DISCENTES_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DISCIPLINAS_POS",
        "columns": [
          {
            "name": "ID_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62c9349d-bcbb-4bc3-9503-6bb265dce41b",
            "sourceColumn": "ID_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "COD_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe4d78da-eb56-45e3-8d88-2186dd9261ad",
            "sourceColumn": "COD_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "583c5033-ffa4-4efd-9a1c-3209943c491e",
            "sourceColumn": "NOME_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "CH_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d915a991-25be-47b3-9a13-8df9a8cc448b",
            "sourceColumn": "CH_TOTAL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "604fc1eb-6dd8-48b1-8e18-8701320f0854",
        "partitions": [
          {
            "name": "V_PRPGP_DISCIPLINAS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCIPLINAS_POS1 = BEE{[Name=\"V_PRPGP_DISCIPLINAS_POS\"]}[Data]",
                "in",
                "    V_PRPGP_DISCIPLINAS_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DOCENTES_POS",
        "columns": [
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc343852-689d-4e74-ac7a-5c392b2da020",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "SIAPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0229dd6c-d0aa-4a7a-8bd1-8b7fd0efc6fb",
            "sourceColumn": "SIAPE",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME_FUNCIONARIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8d8289-a64e-410c-a26f-34c0fde8d157",
            "sourceColumn": "NOME_FUNCIONARIO",
            "summarizeBy": "none"
          },
          {
            "name": "SEXO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90f79339-a3f8-46fd-8a85-d2a7060c6bbf",
            "sourceColumn": "SEXO",
            "summarizeBy": "none"
          },
          {
            "name": "DESCR_CARGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b63ca3d-6a5d-44ce-8e2e-b1b5f6a8ef50",
            "sourceColumn": "DESCR_CARGO",
            "summarizeBy": "none"
          },
          {
            "name": "DT_ADMISSAO_CARGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "93c3ad4e-e2bb-4098-9db6-4c621141a5c0",
            "sourceColumn": "DT_ADMISSAO_CARGO",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f"
                },
                "isDefault": true,
                "relationship": "2ea7bf1a-3305-44e5-bb8a-9739326ad863"
              }
            ]
          },
          {
            "name": "DT_DESLIGAMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4787d5f2-fecb-4e35-acb7-e672eb9e794e",
            "sourceColumn": "DT_DESLIGAMENTO",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35"
                },
                "isDefault": true,
                "relationship": "dbe7e696-971d-40c9-8cc6-add71fc456d2"
              }
            ]
          },
          {
            "name": "NACIONALIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7b8ec4c-597a-4506-bf00-ec3296d276bb",
            "sourceColumn": "NACIONALIDADE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d25995bd-961f-45d0-91b9-8aea0f5164e2",
        "partitions": [
          {
            "name": "V_PRPGP_DOCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DOCENTES_POS1 = BEE{[Name=\"V_PRPGP_DOCENTES_POS\"]}[Data]",
                "in",
                "    V_PRPGP_DOCENTES_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8141c6e-979c-4bce-8e6e-77f697cce0b9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "efee76d4-ff7f-43e2-bd2c-f86548f1d346",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "393d2447-74f7-43f9-993f-9ea5e73484b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "48d5bbcb-1ee5-481e-8c78-7094d05dea9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5b172370-2761-42a6-94cb-89d20545d5b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0c478b88-04b3-4199-9fe4-7bf195c53476",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9a75c085-2446-45ac-bea7-0ba7e759ddb5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88d5a853-2932-45c4-8040-9666bff5ab6c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "268d21d6-dd1d-4b86-afef-257e0d79b4c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4440fea0-0e23-4d90-905f-2b88d5bf570f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c4827acd-e95f-436c-8882-a364c20cd2ba",
                "ordinal": 3
              }
            ],
            "lineageTag": "4e422856-03ce-46d4-a421-3b28a4a0fe54"
          }
        ],
        "isHidden": true,
        "lineageTag": "d6cb6a81-55dd-47b4-b34a-590e1bbce65d",
        "partitions": [
          {
            "name": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DOCENTES_POS'[DT_ADMISSAO_CARGO])), 1, 1), Date(Year(MAX('V_PRPGP_DOCENTES_POS'[DT_ADMISSAO_CARGO])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8f88b0f-2992-413b-8b97-47f3d0374c46",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2f156d57-fbff-4ce1-ae6c-33a2dd0fc373",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "44d35ec9-ab23-457f-8102-5a9106b6d297",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "234ed1be-db5b-40c0-8ec2-137742dbcdd7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "abdf3da5-dfc8-4554-8887-a2b4108c673d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4af882a0-3403-42eb-b6b0-f150c4b2ab60",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6cf43dff-df2b-4d96-920f-2ee5a0a0a02b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "31d8d56f-dd7d-4b02-8c65-98c7cd6dd94e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8715da26-13fa-475c-b3fb-e21029cd4849",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "efc5a7b3-9f37-4094-b369-627ba077d358",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9348bb6e-f62e-40de-ac46-85bce86f2c8d",
                "ordinal": 3
              }
            ],
            "lineageTag": "f4df4657-d931-40ce-9ed1-0d98367f8b72"
          }
        ],
        "isHidden": true,
        "lineageTag": "006745ac-d626-4ca7-959f-393a3583978f",
        "partitions": [
          {
            "name": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DOCENTES_POS'[DT_DESLIGAMENTO])), 1, 1), Date(Year(MAX('V_PRPGP_DOCENTES_POS'[DT_DESLIGAMENTO])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "V_PRPGP_MEMBROS_BANCA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PLANO_ESTUDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "961548d3-a0c8-4721-90e3-509e39d70db4",
            "sourceColumn": "ID_PLANO_ESTUDO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PARTICIP_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90890454-23c1-4ee0-a9c3-c9ee4d632da5",
            "sourceColumn": "ID_PARTICIP_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6529b173-77dc-434e-87a3-7d8011295df1",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb08ae62-2b32-417d-9b45-5508062d8795",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_VINCULO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5a8b9b-79fa-4f2d-ba5b-6672a0a1c8c7",
            "sourceColumn": "TIPO_VINCULO",
            "summarizeBy": "none"
          },
          {
            "name": "SITUACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a09e5a2-7aa8-45af-8094-4ed6f5172ac9",
            "sourceColumn": "SITUACAO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_PARTICIPANTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1cedcd9-0f37-4899-a1de-935edde69c81",
            "sourceColumn": "TIPO_PARTICIPANTE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8250c80c-b9e1-44ac-a53b-6480f45db6e8",
        "partitions": [
          {
            "name": "V_PRPGP_MEMBROS_BANCA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_MEMBROS_BANCA1 = BEE{[Name=\"V_PRPGP_MEMBROS_BANCA\"]}[Data]",
                "in",
                "    V_PRPGP_MEMBROS_BANCA1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PARTICIP_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4e2011a-03dd-4da4-8d5a-722757439128",
            "sourceColumn": "ID_PARTICIP_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_PART_EXTERNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72ff7a30-9e86-47bf-9d4f-3c8761e74f50",
            "sourceColumn": "NOME_PART_EXTERNO",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_INST_ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f06a73f2-f2f0-4bd8-83e5-0f589f51ba10",
            "sourceColumn": "NOME_INST_ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "SIGLA_INST_ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca47dccb-3f1d-4be4-868a-fc7ac2830a3f",
            "sourceColumn": "SIGLA_INST_ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "CPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "837862e6-123d-41b6-b666-023ec5a00ef8",
            "sourceColumn": "CPF",
            "summarizeBy": "none"
          },
          {
            "name": "TITULACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09d462ad-99d6-4f51-85bd-d77b80a35f01",
            "sourceColumn": "TITULACAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85778580-5059-43d6-87c2-4852bba899b8",
        "partitions": [
          {
            "name": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_MEMBROS_EXTERNOS_BANCAS1 = BEE{[Name=\"V_PRPGP_MEMBROS_EXTERNOS_BANCAS\"]}[Data]",
                "in",
                "    V_PRPGP_MEMBROS_EXTERNOS_BANCAS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_PROJETOS_POS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab4d6cdf-94d3-43d2-95e7-eed770e68f31",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "NUM_PROCESSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b6ef86c-0379-4d73-bbbb-728677061193",
            "sourceColumn": "NUM_PROCESSO",
            "summarizeBy": "none"
          },
          {
            "name": "TITULO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73dc54c1-fb37-41e9-9dca-914d5285b4c8",
            "sourceColumn": "TITULO",
            "summarizeBy": "none"
          },
          {
            "name": "CLASSIFICACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3a65ce7-c925-406a-8d84-82d5bfe73f1a",
            "sourceColumn": "CLASSIFICACAO",
            "summarizeBy": "none"
          },
          {
            "name": "SITUACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b391e1e-b0af-4d46-80d0-b3fbe8320417",
            "sourceColumn": "SITUACAO",
            "summarizeBy": "none"
          },
          {
            "name": "DT_INICIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83776a89-c68d-46f0-beb8-87f707faf7c1",
            "sourceColumn": "DT_INICIAL",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5cafaadf-62a2-46ac-964a-951db594eab0"
                },
                "isDefault": true,
                "relationship": "947a2d1d-d9c4-4787-ace1-ebb94e0f1ea7"
              }
            ]
          },
          {
            "name": "DT_CONCLUSAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "60769411-8234-4a76-a5c8-2fee20147a57",
            "sourceColumn": "DT_CONCLUSAO",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_33034433-a6c7-4857-919a-bebeb3fbb368"
                },
                "isDefault": true,
                "relationship": "37c5d120-397a-4c63-a24f-ef417392a3a3"
              }
            ]
          }
        ],
        "lineageTag": "677f56a3-689a-42ce-9af8-a01945892b3e",
        "partitions": [
          {
            "name": "V_PRPGP_PROJETOS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_PROJETOS_POS1 = BEE{[Name=\"V_PRPGP_PROJETOS_POS\"]}[Data]",
                "in",
                "    V_PRPGP_PROJETOS_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5cafaadf-62a2-46ac-964a-951db594eab0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d6132e27-ff63-458f-8dd9-d6e5a2566780",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f53085df-7f07-4767-b52a-212f590d218e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2d233917-ee17-4684-b502-e9d717103406",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "21f74446-eceb-4318-8a5f-7608e45bda3a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c48d6283-5983-4974-ae20-aa7c6d12880e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4b27d42f-4728-4189-891b-86fd2af7b9a2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3c1f8247-7b32-4728-85be-f7137f0779c8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f03222fe-74ed-46b1-a241-e60a02b4308c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a3f53ce1-e803-46e1-a135-305d55e658a8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0ba2f14b-eae7-4f76-88e6-892da7655251",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "93a8c8e1-ac01-44ab-a96d-c742244f1f1a",
                "ordinal": 3
              }
            ],
            "lineageTag": "002b6588-d46b-4420-ae02-c5b92baefb61"
          }
        ],
        "isHidden": true,
        "lineageTag": "12b5adff-8140-4740-b722-0118bb635004",
        "partitions": [
          {
            "name": "LocalDateTable_5cafaadf-62a2-46ac-964a-951db594eab0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_PROJETOS_POS'[DT_INICIAL])), 1, 1), Date(Year(MAX('V_PRPGP_PROJETOS_POS'[DT_INICIAL])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_33034433-a6c7-4857-919a-bebeb3fbb368",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b00372aa-d7b7-41d0-a0ec-8330a1b86b55",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "78b4af39-b319-4197-8f9e-21920586e700",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f000e40f-3991-489e-88ac-22e61174483b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "19e4ec79-6747-4bcd-a587-8b9bf2ddcff2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "70165885-e4d4-40b1-84d8-813860ae063b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cbf29f28-4064-4a0b-bfe5-840b6c12f16c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "898c1fd7-6c4d-4e89-9ebd-fb3a9619bbc7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ee584aa4-25b2-439f-852d-4d399b0257f8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "336f29b4-74db-414d-b5e0-2b77c65cbb8a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c772d9c5-43b6-4e18-bec2-11bba233a529",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bbebeea5-6bb7-40ab-9fac-4c567ca55918",
                "ordinal": 3
              }
            ],
            "lineageTag": "7e50639d-62e5-4df0-8e00-94a2a8318ab0"
          }
        ],
        "isHidden": true,
        "lineageTag": "2900cfcf-2f23-4d5d-a323-52781d70f069",
        "partitions": [
          {
            "name": "LocalDateTable_33034433-a6c7-4857-919a-bebeb3fbb368",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_PROJETOS_POS'[DT_CONCLUSAO])), 1, 1), Date(Year(MAX('V_PRPGP_PROJETOS_POS'[DT_CONCLUSAO])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "V_PRPGP_TIPOS_COTAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c72fadf8-b81b-41bb-8882-5cd9b9e8044c",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO_COTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7838b1d-d43e-4c7e-a077-d8ffd809dc17",
            "sourceColumn": "CODIGO_COTA",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_COTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb4aed60-3371-4968-a5a5-bef044833ad4",
            "sourceColumn": "TIPO_COTA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "50731936-47e1-4621-a346-980e93b29cf1",
        "partitions": [
          {
            "name": "V_PRPGP_TIPOS_COTAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_TIPOS_COTAS1 = BEE{[Name=\"V_PRPGP_TIPOS_COTAS\"]}[Data]",
                "in",
                "    V_PRPGP_TIPOS_COTAS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_TURMAS_POS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ID_DOCENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62427937-0e32-4eef-91cd-d933334390e7",
            "sourceColumn": "ID_DOCENTE",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ff0c7a44-91a6-445e-a414-0067d9458e2e",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7919938-d861-42f2-bac7-f5469569c97c",
            "sourceColumn": "ID_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "ANO_TURMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c99e4412-90db-4944-bea7-a1ebe7a35635",
            "sourceColumn": "ANO_TURMA",
            "summarizeBy": "sum"
          },
          {
            "name": "ENCARGO_DIDATICO_DOCENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c0f09f4-4d89-4bd9-b6bc-23be3e42f4b7",
            "sourceColumn": "ENCARGO_DIDATICO_DOCENTE",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9458ce4b-9310-4320-9f27-25bb767c9b92",
        "partitions": [
          {
            "name": "V_PRPGP_TURMAS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_TURMAS_POS1 = BEE{[Name=\"V_PRPGP_TURMAS_POS\"]}[Data]",
                "in",
                "    V_PRPGP_TURMAS_POS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "999a4e54-0630-4ffa-b226-b82abdc62ef7",
            "sourceColumn": "ID_CONCURSO",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9f12ed-569a-434b-a11e-263c048cdedf",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_OPCAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51ccba1d-a3fe-4077-96a7-736bd972632e",
            "sourceColumn": "ID_OPCAO",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1933250d-bb99-4ab8-a103-79bf371082f5",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO_COTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39792e6b-8a85-46c2-8296-1e2fc8acf3b1",
            "sourceColumn": "CODIGO_COTA",
            "summarizeBy": "none"
          },
          {
            "name": "VAGAS_OFERECIDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84090a51-01f7-4d76-aece-bedd3ce1c8c8",
            "sourceColumn": "VAGAS_OFERECIDAS",
            "summarizeBy": "sum"
          },
          {
            "name": "INSCRITOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dfc4d95a-9415-42f6-8877-00fc644e2972",
            "sourceColumn": "INSCRITOS",
            "summarizeBy": "sum"
          },
          {
            "name": "APROVADOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82f26675-f168-411b-934e-edca2a45e4c6",
            "sourceColumn": "APROVADOS",
            "summarizeBy": "none"
          },
          {
            "name": "MATRICULADOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e934c982-4cdc-4d29-8ffb-e61576a5ba2a",
            "sourceColumn": "MATRICULADOS",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "40c4033c-024c-409f-aa2c-f56ccfb31670",
        "partitions": [
          {
            "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1 = BEE{[Name=\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\"]}[Data]",
                "in",
                "    V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_PROJETOS_POS_ORGAOS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9abdf51-d520-4b43-b23c-3fff83cae5e5",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "COD_ESTRUTURADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a816f018-7fff-41f0-9337-d0d3fde81a64",
            "sourceColumn": "COD_ESTRUTURADO",
            "summarizeBy": "none"
          },
          {
            "name": "NOME_UNIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc68303a-3289-41e8-9b22-af4ba15c8475",
            "sourceColumn": "NOME_UNIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "FUNCAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae66889f-0683-4789-810e-deceefd97a1f",
            "sourceColumn": "FUNCAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "439e653b-5712-4f50-8465-497c0273734e",
        "partitions": [
          {
            "name": "V_PRPGP_PROJETOS_POS_ORGAOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_PROJETOS_POS_ORGAOS1 = BEE{[Name=\"V_PRPGP_PROJETOS_POS_ORGAOS\"]}[Data]",
                "in",
                "    V_PRPGP_PROJETOS_POS_ORGAOS1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PM_PROJETOS_PARTICIPANTES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03609f5b-6723-42f2-b576-2e9869142312",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f8659a22-8d5d-4439-a76a-5a1cf74a3fa8",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aed58778-1b04-44ae-a0d4-2c2f089bdd7a",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "DT_FINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b028f736-2d18-4ece-827c-eec0f853c1b1",
            "sourceColumn": "DT_FINAL",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_80b1c078-b91c-4491-a47d-6e8aca5ec8d5"
                },
                "isDefault": true,
                "relationship": "f8181591-1c9b-45aa-aabb-6e2312d6cb54"
              }
            ]
          }
        ],
        "lineageTag": "950b6f7d-ac16-480e-8d4f-f2b182be4411",
        "partitions": [
          {
            "name": "PM_PROJETOS_PARTICIPANTES",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    PM_PROJETOS_PARTICIPANTES1 = BEE{[Name=\"PM_PROJETOS_PARTICIPANTES\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(PM_PROJETOS_PARTICIPANTES1,{\"DT_INICIAL\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_80b1c078-b91c-4491-a47d-6e8aca5ec8d5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3b7b9b82-3837-4f7c-80a3-6a3546dd8b54",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1568dfbe-8b0d-464d-880f-c176e0e422da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ebfe7df1-57e9-4a16-a926-711d4611a620",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d0dbdb4b-52be-455f-9c94-bf3aed6b3ce8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8ee6ad79-87bb-4277-b495-e7195ca08520",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "932adc5e-0970-4eed-9f98-64a1beba516b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7bf1a816-740f-4aaf-9895-a34c85d53f72",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "99b76757-af8e-4e32-829d-e7b863a53236",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ba0d8839-cc1b-4bd7-9a2e-14ce69c7a648",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "467946d0-34d7-41d0-8bfb-1b4cd69fe7b1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e6964415-f490-40d0-9501-63037db06f28",
                "ordinal": 3
              }
            ],
            "lineageTag": "d9780eae-efff-4e68-9e4b-ed6f5b6a0156"
          }
        ],
        "isHidden": true,
        "lineageTag": "be1d81fb-1af0-423e-9e41-863eaec0854d",
        "partitions": [
          {
            "name": "LocalDateTable_80b1c078-b91c-4491-a47d-6e8aca5ec8d5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('PM_PROJETOS_PARTICIPANTES'[DT_FINAL])), 1, 1), Date(Year(MAX('PM_PROJETOS_PARTICIPANTES'[DT_FINAL])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}