{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"V_PRPGP_CONCURSOS\",\"V_PRPGP_CURSOS_POS\",\"V_PRPGP_DEFESAS\",\"V_PRPGP_DISCENTES_POS\",\"V_PRPGP_DISCIPLINAS_POS\",\"V_PRPGP_DOCENTES_POS\",\"V_PRPGP_MEMBROS_BANCA\",\"V_PRPGP_MEMBROS_EXTERNOS_BANCAS\",\"V_PRPGP_PROJETOS_POS\",\"V_PRPGP_TURMAS_POS\",\"V_PRPGP_PROJETOS_POS_ORGAOS\",\"PM_PROJETOS_PARTICIPANTES\",\"CREDENCIAMENTO_DOCENTES\",\"NAV_UNIDADES\",\"NAV_CENTROS\",\"Medidas\",\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "2ea7bf1a-3305-44e5-bb8a-9739326ad863",
        "fromColumn": "Data ingresso",
        "fromTable": "V_PRPGP_DOCENTES_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f"
      },
      {
        "name": "dbe7e696-971d-40c9-8cc6-add71fc456d2",
        "fromColumn": "Data desligamento",
        "fromTable": "V_PRPGP_DOCENTES_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35"
      },
      {
        "name": "AutoDetected_a6566ff1-61f4-490a-bb0a-06cb95fa56e1",
        "fromColumn": "ID_CURSO",
        "fromTable": "V_PRPGP_DISCENTES_POS",
        "toColumn": "ID_CURSO",
        "toTable": "V_PRPGP_CURSOS_POS"
      },
      {
        "name": "AutoDetected_0baff941-8596-4cc6-8810-be3202bce726",
        "fromColumn": "ID_PLANO_ESTUDO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_PLANO_ESTUDO",
        "toTable": "V_PRPGP_DEFESAS"
      },
      {
        "name": "221f380e-7734-0d6e-9f3c-aa2cef1a255b",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "df979e70-c8a2-7d17-49ea-284dc310c56f",
        "fromColumn": "ID_DOCENTE",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "162a652d-abc0-4fc9-e606-dd76664f2925",
        "fromColumn": "ID_DISCIPLINA",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "ID_DISCIPLINA",
        "toTable": "V_PRPGP_DISCIPLINAS_POS"
      },
      {
        "name": "02b80666-d49a-6b6e-1c45-66507b16dd7f",
        "fromColumn": "ID_PARTICIP_PLANO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_PARTICIP_PLANO",
        "toTable": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS"
      },
      {
        "name": "68437775-5129-0fc8-a259-4ccdcac9f152",
        "fromColumn": "ID_PROJETO",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_PROJETO",
        "toTable": "V_PRPGP_PROJETOS_POS"
      },
      {
        "name": "2b3ef027-1396-c497-cc4c-c0f955097d55",
        "fromColumn": "ID_PROJETO",
        "fromTable": "V_PRPGP_PROJETOS_POS_ORGAOS",
        "toColumn": "ID_PROJETO",
        "toTable": "V_PRPGP_PROJETOS_POS"
      },
      {
        "name": "6da48ca3-16f6-232a-44e4-5752fadf7461",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "67551456-b0b8-61d5-4ead-1612acdf30ea",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "093b44da-e511-45a3-6c1e-2e00f1d4ee14",
        "fromColumn": "ID_CURSO_ALUNO",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_CURSO_ALUNO",
        "toTable": "V_PRPGP_DISCENTES_POS"
      },
      {
        "name": "1112f5ab-f756-8bb5-c47d-69e03ad65564",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "V_PRPGP_MEMBROS_BANCA",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "AutoDetected_19faa936-23d2-4a0c-b251-d4cc20545a6b",
        "fromColumn": "ID_CONTRATO_RH",
        "fromTable": "CREDENCIAMENTO_DOCENTES",
        "toColumn": "ID_CONTRATO_RH",
        "toTable": "V_PRPGP_DOCENTES_POS"
      },
      {
        "name": "89da67bb-9c41-4cd1-aa2c-fb944fae84df",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "ID_CENTRO",
        "fromTable": "NAV_UNIDADES",
        "toColumn": "ID_CENTRO",
        "toTable": "NAV_CENTROS"
      },
      {
        "name": "f80e7c8f-d69b-08e8-266b-6bf04ad35835",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ID_UNIDADE",
        "fromTable": "V_PRPGP_CURSOS_POS",
        "toColumn": "ID_UNIDADE",
        "toTable": "NAV_UNIDADES"
      },
      {
        "name": "cec0c355-600b-3fe7-85d1-ae9c90f1047d",
        "fromColumn": "ID_UNIDADE",
        "fromTable": "V_PRPGP_PROJETOS_POS_ORGAOS",
        "toColumn": "ID_UNIDADE",
        "toTable": "NAV_UNIDADES"
      },
      {
        "name": "467491a2-3f9f-401d-af76-0cc4142a4b25",
        "fromColumn": "Data",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_38ed732a-695c-4c42-86f7-80227cb349ca"
      },
      {
        "name": "eedeea2f-d048-fadd-1bd9-ab24d2511415",
        "fromColumn": "Data início atuação programa",
        "fromTable": "CREDENCIAMENTO_DOCENTES",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "22207ed2-8f6d-3f50-92c8-f96531faa935",
        "fromColumn": "Data fim atuação programa",
        "fromTable": "CREDENCIAMENTO_DOCENTES",
        "isActive": false,
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "b1e9ad96-c532-e9ba-7fcf-e6e14f6e346d",
        "fromColumn": "Data defesa",
        "fromTable": "V_PRPGP_DEFESAS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "9ed07c28-e43c-4bf9-b87d-f8adbab3a11e",
        "fromColumn": "Data ingresso",
        "fromTable": "V_PRPGP_DISCENTES_POS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_519d3b9f-5797-43d5-9959-c15ab834d47a"
      },
      {
        "name": "a393306c-dd44-bc82-5479-2607c0298bad",
        "fromColumn": "Data",
        "fromTable": "V_PRPGP_CONCURSOS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "3ffc0afc-0ed1-4ab4-9c6e-cb4268acdcc3",
        "fromColumn": "Data fim participação",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_61ca13bd-66ed-497e-a3c1-5b31731daf9b"
      },
      {
        "name": "dddb166b-a03f-4f1f-b58b-e77e98984686",
        "fromColumn": "Data início participação",
        "fromTable": "PM_PROJETOS_PARTICIPANTES",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_95112233-7078-4557-bc93-37e2b6ea704c"
      },
      {
        "name": "c2355384-e57b-e6fd-3083-6da5fcceaffd",
        "fromColumn": "Data início",
        "fromTable": "V_PRPGP_PROJETOS_POS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "efbbe0ea-b486-f968-fb55-78b4511ca896",
        "fromColumn": "Data fim",
        "fromTable": "V_PRPGP_PROJETOS_POS",
        "isActive": false,
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "6ff031ce-d9ee-5115-ba3b-3639cb864bba",
        "fromColumn": "Data turma",
        "fromTable": "V_PRPGP_TURMAS_POS",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "2765159a-0002-06b6-ffc6-16e21bcd3859",
        "fromColumn": "ID_CONC_EDICAO",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "ID_CONC_EDICAO",
        "toTable": "V_PRPGP_CONCURSOS"
      },
      {
        "name": "4cc67295-79ed-0c68-a616-7f9b94e3d0f5",
        "fromColumn": "ID_CURSO",
        "fromTable": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "toColumn": "ID_CURSO",
        "toTable": "V_PRPGP_CURSOS_POS"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_53f11cfa-ca4c-4abc-9af5-9af882a32f14",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bbdc223c-d11c-450e-973b-dd31cb148ad3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ffd875bf-5b7b-415b-9a61-3bd0db6cdfa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3098504c-603f-4e1b-92da-93640009f742",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ecc9a347-5eec-46b2-9811-7e06f1dd28cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dc6e667d-cd34-47ed-811f-819ec616b634",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8475cfce-535b-4295-9ac1-e949d050e481",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8aa60150-d273-40ab-b4f9-98ad3865cc0c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "469cfe5d-d0f8-46ac-88a0-8cb0874ec051",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a0db6530-724b-46d9-af85-4b930e7741c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5508a7b4-a333-4cad-9ded-68f03fd353d5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f9b57742-e09c-45ef-bc02-52d01b038997",
                "ordinal": 3
              }
            ],
            "lineageTag": "3543001d-5bd1-4d55-92dc-5702a5063dd9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e2c5fa93-7bd9-44ef-aa93-afb2d2bb974d",
        "partitions": [
          {
            "name": "DateTableTemplate_53f11cfa-ca4c-4abc-9af5-9af882a32f14",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_CONCURSOS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9178df64-d416-45ea-9b8e-eb78c33eedf4",
            "sourceColumn": "ID_CONCURSO",
            "summarizeBy": "sum"
          },
          {
            "name": "Concurso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5317f253-d81f-4011-8d29-68884731e1b5",
            "sourceColumn": "Concurso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ee9f0f0-71d1-4803-ae49-9fa5ba30332c",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "aa84dec6-f13e-47b6-9d1a-058cc8847e93",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "Edição concurso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afe4130c-be59-4473-8ca8-841bcae7d000",
            "sourceColumn": "Edição concurso",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4e2b0add-d42d-48c4-b5b6-e997ae6cbef7",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b016d5a-46b3-48e5-a6a4-08c77803f102",
        "partitions": [
          {
            "name": "V_PRPGP_CONCURSOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_CONCURSOS1 = BEE{[Name=\"V_PRPGP_CONCURSOS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_CONCURSOS1,{{\"DESCR_CONC_EDICAO\", \"Edição concurso\"}, {\"DESCR_CONCURSO\", \"Concurso\"}, {\"ANO\", \"Ano\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Data\", each Date.From(Text.From([Ano], \"pt-BR\")), type date)",
                "in",
                "    #\"Inserted Date\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_CURSOS_POS",
        "columns": [
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1c212997-5966-4c49-9f0d-eb084fe16c81",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "Código curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5a56728-37d0-4645-82dd-83e8b9009c45",
            "sourceColumn": "Código curso",
            "summarizeBy": "none"
          },
          {
            "name": "Nome curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a344cffe-1f4c-41f4-be48-ad27c3a13c45",
            "sourceColumn": "Nome curso",
            "summarizeBy": "none"
          },
          {
            "name": "Nível curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "279c7aaf-10d2-46ec-b950-68261f807990",
            "sourceColumn": "Nível curso",
            "summarizeBy": "none"
          },
          {
            "name": "Modalidade curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acbec8b8-ae81-464d-b67f-3acb54d7b93f",
            "sourceColumn": "Modalidade curso",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80f3a514-e371-4d05-8abd-1d028365663a",
            "sourceColumn": "Classificação curso",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "99f49a10-65d1-4198-85d2-254ef6e24108",
            "sourceColumn": "ID_UNIDADE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7f424f93-fe10-4152-8ee3-899949d932f9",
        "partitions": [
          {
            "name": "V_PRPGP_CURSOS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_CURSOS_POS1 = BEE{[Name=\"V_PRPGP_CURSOS_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_CURSOS_POS1,{{\"COD_CURSO\", \"Código curso\"}, {\"MODALIDADE_CURSO\", \"Modalidade curso\"}, {\"CLASSIFICACAO_CURSO\", \"Classificação curso\"}, {\"NIVEL_CURSO\", \"Nível curso\"}, {\"NOME_CURSO\", \"Nome curso\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DEFESAS",
        "columns": [
          {
            "name": "ID_PLANO_ESTUDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1abf5ad2-3dcb-4411-b416-aa78eebc295e",
            "sourceColumn": "ID_PLANO_ESTUDO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "585535c8-c66c-4a07-90a4-02511eb430fa",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "sum"
          },
          {
            "name": "Data defesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a3cc67cb-804a-46e1-af44-17d1cea7e349",
            "sourceColumn": "Data defesa",
            "summarizeBy": "none"
          },
          {
            "name": "Situação plano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e13cf5e-6716-4302-840f-3e901b031d3d",
            "sourceColumn": "Situação plano",
            "summarizeBy": "none"
          },
          {
            "name": "Situação defesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81a6c5bf-baf8-465d-a9b5-de6517e6c9d9",
            "sourceColumn": "Situação defesa",
            "summarizeBy": "none"
          },
          {
            "name": "Contagem de Defesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CALCULATE(COUNTROWS(V_PRPGP_DEFESAS), ALLEXCEPT(V_PRPGP_DEFESAS, V_PRPGP_DEFESAS[Situação defesa]))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9d275bf6-75b3-4d7e-a78e-4a483da381de",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "2f1fedb7-dace-478f-8610-18ad19029bda",
        "partitions": [
          {
            "name": "V_PRPGP_DEFESAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DEFESAS1 = BEE{[Name=\"V_PRPGP_DEFESAS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DEFESAS1,{{\"DH_DEFESA\", \"Data defesa\"}, {\"SITUACAO_DEFESA\", \"Situação defesa\"}, {\"SITUACAO_PLANO\", \"Situação plano\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DISCENTES_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8fc61f1e-182f-4a49-9d96-c9bf45265f8b",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "Matrícula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e9d438-3452-4a42-aa72-6311088b2728",
            "sourceColumn": "Matrícula",
            "summarizeBy": "none"
          },
          {
            "name": "Nome aluno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f4b775-a258-4311-85c4-ab20c721b5a0",
            "sourceColumn": "Nome aluno",
            "summarizeBy": "none"
          },
          {
            "name": "Ano ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3103874-35f6-4f66-a93c-b1b07371309e",
            "sourceColumn": "Ano ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano saída",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98457c3d-3952-4741-98ba-0192f19d354c",
            "sourceColumn": "Ano saída",
            "summarizeBy": "none"
          },
          {
            "name": "Forma saída",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d55b86-2e12-47ac-8d3f-8e56efa72293",
            "sourceColumn": "Forma saída",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e50fe787-0b41-4d4e-9e7d-cc1b35d057f7",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "Nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"V_PRPGP_DISCENTES_POS\",\"TableItemName\":\"Nacionalidade (agrupada)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "cadf0df1-88b0-4a21-8518-5edc582e972a",
            "sourceColumn": "Nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Nacionalidade (agrupada)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"v\",\"Entity\":\"V_PRPGP_DISCENTES_POS\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"Nacionalidade\"}}],\"GroupItems\":[{\"DisplayName\":\"(Em branco)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Alemã(ão) & Angolano(a) & Argentino(a) & Boliviano(a) & ...\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"Nacionalidade\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Alemã(ão)'\"}}],[{\"Literal\":{\"Value\":\"'Angolano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Argentino(a)'\"}}],[{\"Literal\":{\"Value\":\"'Boliviano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Cabo-verdiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Camaronês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Chileno(a)'\"}}],[{\"Literal\":{\"Value\":\"'Colombiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Cubano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Equatoriano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Espanhol(a)'\"}}],[{\"Literal\":{\"Value\":\"'Ganês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Guatemalteco(a)'\"}}],[{\"Literal\":{\"Value\":\"'Guianês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Guineense'\"}}],[{\"Literal\":{\"Value\":\"'Haitiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Hondurenho(a)'\"}}],[{\"Literal\":{\"Value\":\"'Indiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Italiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Mexicano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Moçambicano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Nicaraguense'\"}}],[{\"Literal\":{\"Value\":\"'Nigeriano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Norte Americano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paquistanês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paraguaio(a)'\"}}],[{\"Literal\":{\"Value\":\"'Paraguaio(a) Naturalizado(a)'\"}}],[{\"Literal\":{\"Value\":\"'Peruano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Português(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Salvadorenho(a)'\"}}],[{\"Literal\":{\"Value\":\"'São-tomense'\"}}],[{\"Literal\":{\"Value\":\"'Senegalês(esa)'\"}}],[{\"Literal\":{\"Value\":\"'Surinamês(a)'\"}}],[{\"Literal\":{\"Value\":\"'Timorense'\"}}],[{\"Literal\":{\"Value\":\"'Tunisiano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Uruguaio(a)'\"}}],[{\"Literal\":{\"Value\":\"'Uruguaio(a) Naturalizado(a)'\"}}],[{\"Literal\":{\"Value\":\"'Venezuelano(a)'\"}}],[{\"Literal\":{\"Value\":\"'Venezuelano(a) Naturalizado(a)'\"}}]]}}},{\"DisplayName\":\"Brasileiro(a) & Brasileiro(a) Naturalizado(a)\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"v\"}},\"Property\":\"Nacionalidade\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Brasileiro(a)'\"}}],[{\"Literal\":{\"Value\":\"'Brasileiro(a) Naturalizado(a)'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('V_PRPGP_DISCENTES_POS'[Nacionalidade]),",
              "\t\"(Em branco)\",",
              "\t'V_PRPGP_DISCENTES_POS'[Nacionalidade] IN {\"Alemã(ão)\",",
              "\t\t\"Angolano(a)\",",
              "\t\t\"Argentino(a)\",",
              "\t\t\"Boliviano(a)\",",
              "\t\t\"Cabo-verdiano(a)\",",
              "\t\t\"Camaronês(esa)\",",
              "\t\t\"Chileno(a)\",",
              "\t\t\"Colombiano(a)\",",
              "\t\t\"Cubano(a)\",",
              "\t\t\"Equatoriano(a)\",",
              "\t\t\"Espanhol(a)\",",
              "\t\t\"Ganês(a)\",",
              "\t\t\"Guatemalteco(a)\",",
              "\t\t\"Guianês(esa)\",",
              "\t\t\"Guineense\",",
              "\t\t\"Haitiano(a)\",",
              "\t\t\"Hondurenho(a)\",",
              "\t\t\"Indiano(a)\",",
              "\t\t\"Italiano(a)\",",
              "\t\t\"Mexicano(a)\",",
              "\t\t\"Moçambicano(a)\",",
              "\t\t\"Nicaraguense\",",
              "\t\t\"Nigeriano(a)\",",
              "\t\t\"Norte Americano(a)\",",
              "\t\t\"Paquistanês(a)\",",
              "\t\t\"Paraguaio(a)\",",
              "\t\t\"Paraguaio(a) Naturalizado(a)\",",
              "\t\t\"Peruano(a)\",",
              "\t\t\"Português(esa)\",",
              "\t\t\"Salvadorenho(a)\",",
              "\t\t\"São-tomense\",",
              "\t\t\"Senegalês(esa)\",",
              "\t\t\"Surinamês(a)\",",
              "\t\t\"Timorense\",",
              "\t\t\"Tunisiano(a)\",",
              "\t\t\"Uruguaio(a)\",",
              "\t\t\"Uruguaio(a) Naturalizado(a)\",",
              "\t\t\"Venezuelano(a)\",",
              "\t\t\"Venezuelano(a) Naturalizado(a)\"},",
              "\t\"Alemã(ão) & Angolano(a) & Argentino(a) & Boliviano(a) & ...\",",
              "\t'V_PRPGP_DISCENTES_POS'[Nacionalidade] IN {\"Brasileiro(a)\",",
              "\t\t\"Brasileiro(a) Naturalizado(a)\"},",
              "\t\"Brasileiro(a) & Brasileiro(a) Naturalizado(a)\",",
              "\t'V_PRPGP_DISCENTES_POS'[Nacionalidade]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "V_PRPGP_DISCENTES_POS"
                          }
                        },
                        "Property": "Nacionalidade"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ce12d12c-9ac8-4377-b60f-28ed6081b14c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "7a8401e9-676c-4dd0-8a7d-c2128bae87c5",
            "sourceColumn": "Data ingresso",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_519d3b9f-5797-43d5-9959-c15ab834d47a"
                },
                "isDefault": true,
                "relationship": "9ed07c28-e43c-4bf9-b87d-f8adbab3a11e"
              }
            ]
          }
        ],
        "lineageTag": "68361baf-98db-4955-8b69-d6584362a50b",
        "partitions": [
          {
            "name": "V_PRPGP_DISCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCENTES_POS1 = BEE{[Name=\"V_PRPGP_DISCENTES_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DISCENTES_POS1,{{\"ANO_EVASAO\", \"Ano saída\"}, {\"ANO_INGRESSO\", \"Ano ingresso\"}, {\"FORMA_EVASAO\", \"Forma saída\"}, {\"MATRICULA\", \"Matrícula\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"MODALIDADE_CURSO\", \"NIVEL_CURSO\", \"NOME_CURSO\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"NACIONALIDADE\", \"Nacionalidade\"}, {\"NOME_ALUNO\", \"Nome aluno\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns1\", \"Data\", each Date.From(Text.From([Ano ingresso], \"pt-BR\")), type date),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Date\",{{\"Data\", \"Data ingresso\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DISCIPLINAS_POS",
        "columns": [
          {
            "name": "ID_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62c9349d-bcbb-4bc3-9503-6bb265dce41b",
            "sourceColumn": "ID_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "Código disciplina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe4d78da-eb56-45e3-8d88-2186dd9261ad",
            "sourceColumn": "Código disciplina",
            "summarizeBy": "none"
          },
          {
            "name": "Nome disciplina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "583c5033-ffa4-4efd-9a1c-3209943c491e",
            "sourceColumn": "Nome disciplina",
            "summarizeBy": "none"
          },
          {
            "name": "Carga horária",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d915a991-25be-47b3-9a13-8df9a8cc448b",
            "sourceColumn": "Carga horária",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "604fc1eb-6dd8-48b1-8e18-8701320f0854",
        "partitions": [
          {
            "name": "V_PRPGP_DISCIPLINAS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DISCIPLINAS_POS1 = BEE{[Name=\"V_PRPGP_DISCIPLINAS_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DISCIPLINAS_POS1,{{\"CH_TOTAL\", \"Carga horária\"}, {\"COD_DISCIPLINA\", \"Código disciplina\"}, {\"NOME_DISCIPLINA\", \"Nome disciplina\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_DOCENTES_POS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc343852-689d-4e74-ac7a-5c392b2da020",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "SIAPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0229dd6c-d0aa-4a7a-8bd1-8b7fd0efc6fb",
            "sourceColumn": "SIAPE",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8d8289-a64e-410c-a26f-34c0fde8d157",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Gênero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90f79339-a3f8-46fd-8a85-d2a7060c6bbf",
            "sourceColumn": "Gênero",
            "summarizeBy": "none"
          },
          {
            "name": "Cargo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b63ca3d-6a5d-44ce-8e2e-b1b5f6a8ef50",
            "sourceColumn": "Cargo",
            "summarizeBy": "none"
          },
          {
            "name": "Data ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "93c3ad4e-e2bb-4098-9db6-4c621141a5c0",
            "sourceColumn": "Data ingresso",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f"
                },
                "isDefault": true,
                "relationship": "2ea7bf1a-3305-44e5-bb8a-9739326ad863"
              }
            ]
          },
          {
            "name": "Data desligamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4787d5f2-fecb-4e35-acb7-e672eb9e794e",
            "sourceColumn": "Data desligamento",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35"
                },
                "isDefault": true,
                "relationship": "dbe7e696-971d-40c9-8cc6-add71fc456d2"
              }
            ]
          },
          {
            "name": "Nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7b8ec4c-597a-4506-bf00-ec3296d276bb",
            "sourceColumn": "Nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Ano ingresso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02623384-597b-4fde-9a8f-563bae68b246",
            "sourceColumn": "Ano ingresso",
            "summarizeBy": "none"
          },
          {
            "name": "Ano desligamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d79eb06-8548-43d9-bd78-311e5ea25302",
            "sourceColumn": "Ano desligamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d25995bd-961f-45d0-91b9-8aea0f5164e2",
        "partitions": [
          {
            "name": "V_PRPGP_DOCENTES_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_DOCENTES_POS1 = BEE{[Name=\"V_PRPGP_DOCENTES_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_DOCENTES_POS1,{{\"DESCR_CARGO\", \"Cargo\"}, {\"DT_ADMISSAO_CARGO\", \"Data ingresso\"}, {\"DT_DESLIGAMENTO\", \"Data desligamento\"}, {\"NACIONALIDADE\", \"Nacionalidade\"}, {\"SEXO\", \"Gênero\"}, {\"NOME_FUNCIONARIO\", \"Nome\"}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Renamed Columns\", \"Ano ingresso\", each Date.Year([Data ingresso]), Int64.Type),",
                "    #\"Inserted Year1\" = Table.AddColumn(#\"Inserted Year\", \"Ano desligamento\", each Date.Year([Data desligamento]), Int64.Type)",
                "in",
                "    #\"Inserted Year1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8141c6e-979c-4bce-8e6e-77f697cce0b9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "efee76d4-ff7f-43e2-bd2c-f86548f1d346",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "393d2447-74f7-43f9-993f-9ea5e73484b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "48d5bbcb-1ee5-481e-8c78-7094d05dea9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5b172370-2761-42a6-94cb-89d20545d5b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0c478b88-04b3-4199-9fe4-7bf195c53476",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9a75c085-2446-45ac-bea7-0ba7e759ddb5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88d5a853-2932-45c4-8040-9666bff5ab6c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "268d21d6-dd1d-4b86-afef-257e0d79b4c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4440fea0-0e23-4d90-905f-2b88d5bf570f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c4827acd-e95f-436c-8882-a364c20cd2ba",
                "ordinal": 3
              }
            ],
            "lineageTag": "4e422856-03ce-46d4-a421-3b28a4a0fe54"
          }
        ],
        "isHidden": true,
        "lineageTag": "d6cb6a81-55dd-47b4-b34a-590e1bbce65d",
        "partitions": [
          {
            "name": "LocalDateTable_78d1081d-2983-4240-b7e8-2d69e045838f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DOCENTES_POS'[Data ingresso])), 1, 1), Date(Year(MAX('V_PRPGP_DOCENTES_POS'[Data ingresso])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8f88b0f-2992-413b-8b97-47f3d0374c46",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2f156d57-fbff-4ce1-ae6c-33a2dd0fc373",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "44d35ec9-ab23-457f-8102-5a9106b6d297",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "234ed1be-db5b-40c0-8ec2-137742dbcdd7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "abdf3da5-dfc8-4554-8887-a2b4108c673d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4af882a0-3403-42eb-b6b0-f150c4b2ab60",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6cf43dff-df2b-4d96-920f-2ee5a0a0a02b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "31d8d56f-dd7d-4b02-8c65-98c7cd6dd94e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8715da26-13fa-475c-b3fb-e21029cd4849",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "efc5a7b3-9f37-4094-b369-627ba077d358",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9348bb6e-f62e-40de-ac46-85bce86f2c8d",
                "ordinal": 3
              }
            ],
            "lineageTag": "f4df4657-d931-40ce-9ed1-0d98367f8b72"
          }
        ],
        "isHidden": true,
        "lineageTag": "006745ac-d626-4ca7-959f-393a3583978f",
        "partitions": [
          {
            "name": "LocalDateTable_b6e4c7ec-07b2-43a4-ad00-0f28d4746a35",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DOCENTES_POS'[Data desligamento])), 1, 1), Date(Year(MAX('V_PRPGP_DOCENTES_POS'[Data desligamento])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "V_PRPGP_MEMBROS_BANCA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PLANO_ESTUDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "961548d3-a0c8-4721-90e3-509e39d70db4",
            "sourceColumn": "ID_PLANO_ESTUDO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PARTICIP_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "90890454-23c1-4ee0-a9c3-c9ee4d632da5",
            "sourceColumn": "ID_PARTICIP_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6529b173-77dc-434e-87a3-7d8011295df1",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb08ae62-2b32-417d-9b45-5508062d8795",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo vínculo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5a8b9b-79fa-4f2d-ba5b-6672a0a1c8c7",
            "sourceColumn": "Tipo vínculo",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a09e5a2-7aa8-45af-8094-4ed6f5172ac9",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo participante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1cedcd9-0f37-4899-a1de-935edde69c81",
            "sourceColumn": "Tipo participante",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8250c80c-b9e1-44ac-a53b-6480f45db6e8",
        "partitions": [
          {
            "name": "V_PRPGP_MEMBROS_BANCA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_MEMBROS_BANCA1 = BEE{[Name=\"V_PRPGP_MEMBROS_BANCA\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_MEMBROS_BANCA1,{{\"SITUACAO\", \"Situação\"}, {\"TIPO_PARTICIPANTE\", \"Tipo participante\"}, {\"TIPO_VINCULO\", \"Tipo vínculo\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PARTICIP_PLANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a4e2011a-03dd-4da4-8d5a-722757439128",
            "sourceColumn": "ID_PARTICIP_PLANO",
            "summarizeBy": "none"
          },
          {
            "name": "Nome participante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72ff7a30-9e86-47bf-9d4f-3c8761e74f50",
            "sourceColumn": "Nome participante",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Instituição origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f06a73f2-f2f0-4bd8-83e5-0f589f51ba10",
            "sourceColumn": "Nome Instituição origem",
            "summarizeBy": "none"
          },
          {
            "name": "Sigla Instituição origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca47dccb-3f1d-4be4-868a-fc7ac2830a3f",
            "sourceColumn": "Sigla Instituição origem",
            "summarizeBy": "none"
          },
          {
            "name": "Titulação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09d462ad-99d6-4f51-85bd-d77b80a35f01",
            "sourceColumn": "Titulação",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85778580-5059-43d6-87c2-4852bba899b8",
        "partitions": [
          {
            "name": "V_PRPGP_MEMBROS_EXTERNOS_BANCAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_MEMBROS_EXTERNOS_BANCAS1 = BEE{[Name=\"V_PRPGP_MEMBROS_EXTERNOS_BANCAS\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(V_PRPGP_MEMBROS_EXTERNOS_BANCAS1,{\"CPF\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"TITULACAO\", \"Titulação\"}, {\"SIGLA_INST_ORIGEM\", \"Sigla Instituição origem\"}, {\"NOME_INST_ORIGEM\", \"Nome Instituição origem\"}, {\"NOME_PART_EXTERNO\", \"Nome participante\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_PROJETOS_POS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ab4d6cdf-94d3-43d2-95e7-eed770e68f31",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "Número processo PEN-SIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b6ef86c-0379-4d73-bbbb-728677061193",
            "sourceColumn": "Número processo PEN-SIE",
            "summarizeBy": "none"
          },
          {
            "name": "Título",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73dc54c1-fb37-41e9-9dca-914d5285b4c8",
            "sourceColumn": "Título",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação projeto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3a65ce7-c925-406a-8d84-82d5bfe73f1a",
            "sourceColumn": "Classificação projeto",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b391e1e-b0af-4d46-80d0-b3fbe8320417",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "Data início",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83776a89-c68d-46f0-beb8-87f707faf7c1",
            "sourceColumn": "Data início",
            "summarizeBy": "none"
          },
          {
            "name": "Data fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "60769411-8234-4a76-a5c8-2fee20147a57",
            "sourceColumn": "Data fim",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "677f56a3-689a-42ce-9af8-a01945892b3e",
        "partitions": [
          {
            "name": "V_PRPGP_PROJETOS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_PROJETOS_POS1 = BEE{[Name=\"V_PRPGP_PROJETOS_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_PROJETOS_POS1,{{\"CLASSIFICACAO\", \"Classificação projeto\"}, {\"DT_INICIAL\", \"Data início\"}, {\"DT_CONCLUSAO\", \"Data fim\"}, {\"NUM_PROCESSO\", \"Número processo PEN-SIE\"}, {\"SITUACAO\", \"Situação\"}, {\"TITULO\", \"Título\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_TURMAS_POS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID_DOCENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62427937-0e32-4eef-91cd-d933334390e7",
            "sourceColumn": "ID_DOCENTE",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff0c7a44-91a6-445e-a414-0067d9458e2e",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_DISCIPLINA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f7919938-d861-42f2-bac7-f5469569c97c",
            "sourceColumn": "ID_DISCIPLINA",
            "summarizeBy": "none"
          },
          {
            "name": "Ano turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c99e4412-90db-4944-bea7-a1ebe7a35635",
            "sourceColumn": "Ano turma",
            "summarizeBy": "none"
          },
          {
            "name": "Encargo didático docente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c0f09f4-4d89-4bd9-b6bc-23be3e42f4b7",
            "sourceColumn": "Encargo didático docente",
            "summarizeBy": "sum"
          },
          {
            "name": "Data turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "7cb9eca7-36f0-4b70-8196-863eecc6cf5b",
            "sourceColumn": "Data turma",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9458ce4b-9310-4320-9f27-25bb767c9b92",
        "partitions": [
          {
            "name": "V_PRPGP_TURMAS_POS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_TURMAS_POS1 = BEE{[Name=\"V_PRPGP_TURMAS_POS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_TURMAS_POS1,{{\"ANO_TURMA\", \"Ano turma\"}, {\"ENCARGO_DIDATICO_DOCENTE\", \"Encargo didático docente\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Data turma\", each Date.From(Text.From([Ano turma], \"pt-BR\")), type date)",
                "in",
                "    #\"Inserted Date\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_PRPGP_PROJETOS_POS_ORGAOS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9abdf51-d520-4b43-b23c-3fff83cae5e5",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "Nome unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc68303a-3289-41e8-9b22-af4ba15c8475",
            "sourceColumn": "Nome unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Função",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae66889f-0683-4789-810e-deceefd97a1f",
            "sourceColumn": "Função",
            "summarizeBy": "none"
          },
          {
            "name": "ID_UNIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f40769b1-e522-479b-a20a-ca349c9dc048",
            "sourceColumn": "ID_UNIDADE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "439e653b-5712-4f50-8465-497c0273734e",
        "partitions": [
          {
            "name": "V_PRPGP_PROJETOS_POS_ORGAOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_PROJETOS_POS_ORGAOS1 = BEE{[Name=\"V_PRPGP_PROJETOS_POS_ORGAOS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(V_PRPGP_PROJETOS_POS_ORGAOS1,{{\"COD_ESTRUTURADO\", \"Código estruturado\"}, {\"FUNCAO\", \"Função\"}, {\"NOME_UNIDADE\", \"Nome unidade\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Código estruturado\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PM_PROJETOS_PARTICIPANTES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID_PROJETO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "03609f5b-6723-42f2-b576-2e9869142312",
            "sourceColumn": "ID_PROJETO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO_ALUNO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8659a22-8d5d-4439-a76a-5a1cf74a3fa8",
            "sourceColumn": "ID_CURSO_ALUNO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "aed58778-1b04-44ae-a0d4-2c2f089bdd7a",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "Data fim participação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b028f736-2d18-4ece-827c-eec0f853c1b1",
            "sourceColumn": "Data fim participação",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_61ca13bd-66ed-497e-a3c1-5b31731daf9b"
                },
                "isDefault": true,
                "relationship": "3ffc0afc-0ed1-4ab4-9c6e-cb4268acdcc3"
              }
            ]
          },
          {
            "name": "Data início participação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e055cf4c-9108-4dd3-891a-593e3001920b",
            "sourceColumn": "Data início participação",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_95112233-7078-4557-bc93-37e2b6ea704c"
                },
                "isDefault": true,
                "relationship": "dddb166b-a03f-4f1f-b58b-e77e98984686"
              }
            ]
          }
        ],
        "lineageTag": "950b6f7d-ac16-480e-8d4f-f2b182be4411",
        "partitions": [
          {
            "name": "PM_PROJETOS_PARTICIPANTES",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    PM_PROJETOS_PARTICIPANTES1 = BEE{[Name=\"PM_PROJETOS_PARTICIPANTES\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(PM_PROJETOS_PARTICIPANTES1,{{\"DT_FINAL\", \"Data fim participação\"}, {\"DT_INICIAL\", \"Data início participação\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CREDENCIAMENTO_DOCENTES",
        "columns": [
          {
            "name": "ID_CREDENCIAMENTO_DOCENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "418ba751-b5c1-4bd3-93d1-8ec22eb13f1f",
            "sourceColumn": "ID_CREDENCIAMENTO_DOCENTE",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_UNIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a15d962-f439-45d8-b550-3d566c3566d9",
            "sourceColumn": "ID_UNIDADE",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome programa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82bdbc9a-3f43-4326-bc0b-48dc00e90e5e",
            "sourceColumn": "Nome programa",
            "summarizeBy": "none"
          },
          {
            "name": "Vínculo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "958ed362-ac34-4af7-b694-04a17591ecd9",
            "sourceColumn": "Vínculo",
            "summarizeBy": "none"
          },
          {
            "name": "Data fim atuação programa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "723f412b-3619-4af4-83c4-a231cea63da7",
            "sourceColumn": "Data fim atuação programa",
            "summarizeBy": "none"
          },
          {
            "name": "Data início atuação programa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f81ab1d2-d706-4b2d-a792-ddc5642de13d",
            "sourceColumn": "Data início atuação programa",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PESSOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "13728343-5f2d-4692-9af6-9e92a10e9ad6",
            "sourceColumn": "ID_PESSOA",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_CONTRATO_RH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7dc92c8e-3f4e-4ad0-a53c-7cad0f53712c",
            "sourceColumn": "ID_CONTRATO_RH",
            "summarizeBy": "none"
          },
          {
            "name": "SIAPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e84024e1-9e58-40e3-83ed-5cdb047a97dc",
            "sourceColumn": "SIAPE",
            "summarizeBy": "none"
          },
          {
            "name": "Nome docente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea19faa5-6f25-45ba-bc85-f9585dc0f62d",
            "sourceColumn": "Nome docente",
            "summarizeBy": "none"
          },
          {
            "name": "Titulação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef29f7f9-f0f7-49ef-bf4c-78b1495d99ab",
            "sourceColumn": "Titulação",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "23e4bd8d-5d94-45de-88d3-628f436d72f8",
        "partitions": [
          {
            "name": "CREDENCIAMENTO_DOCENTES",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    CREDENCIAMENTO_DOCENTES1 = BEE{[Name=\"CREDENCIAMENTO_DOCENTES\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(CREDENCIAMENTO_DOCENTES1,{\"CH_SEMANAL\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"NOME_PESSOA\", \"Nome docente\"}, {\"PROGRAMA\", \"Nome programa\"}, {\"TITULACAO\", \"Titulação\"}, {\"DT_FIM\", \"Data início atuação programa\"}, {\"DT_INICIO\", \"Data fim atuação programa\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"EDITAL\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"MATR_EXTERNA\", \"SIAPE\"}, {\"TIPO_CREDENCIAMENTO\", \"Vínculo\"}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"COD_ESTRUTURADO\"})",
                "in",
                "    #\"Removed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NAV_UNIDADES",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_UNIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "14d82178-c87e-4415-8dfb-763f117a0eaf",
            "sourceColumn": "ID_UNIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "Código unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b26fc2d-e7fc-4043-a88d-fb3e89fc3652",
            "sourceColumn": "Código unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7f0bf11-b3b0-442e-9cbc-a5fab55d236a",
            "sourceColumn": "Nome Unidade",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CENTRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24ff070d-d4ce-4f84-87ee-ec08a78a07d6",
            "sourceColumn": "ID_CENTRO",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "186fcef7-8e9d-458d-8db4-8432ec7ce270",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c311a3a8-37a3-458b-80e9-c3030a03eaf7",
            "sourceColumn": "Tipo Unidade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3482d8a9-69e4-4c1c-b1f6-bdacc4b2e630",
        "partitions": [
          {
            "name": "NAV_UNIDADES",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    NAV_UNIDADES1 = BEE{[Name=\"NAV_UNIDADES\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(NAV_UNIDADES1,{\"ID_PREDIO\", \"ID_PROGRAMA\", \"ID_NIVEL_ENSINO\", \"DT_ADESAO_PGD\", \"BEE.NAV_CENTROS\", \"BEE.NAV_GRUPOS_UNIDADES\", \"ID_UNIDADE_SUP\", \"ID_GRUPO_UNIDADE\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"COD_ESTRUTURADO\", \"Código unidade\"}, {\"NOME_UNIDADE\", \"Nome Unidade\"}, {\"SITUACAO\", \"Situação\"}, {\"TIPO_UNIDADE\", \"Tipo Unidade\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NAV_CENTROS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CENTRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d75bd2a4-9bc3-45f7-adfe-84442692ec04",
            "sourceColumn": "ID_CENTRO",
            "summarizeBy": "none"
          },
          {
            "name": "Código centro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fae36ac5-81f5-43cf-a315-1772194b6b26",
            "sourceColumn": "Código centro",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Centro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64caa6df-2bf1-4866-907b-ecdd720f44d3",
            "sourceColumn": "Nome Centro",
            "summarizeBy": "none"
          },
          {
            "name": "Sigla Centro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "444c67eb-5ab1-4c72-a833-0e2ee5fd85f0",
            "sourceColumn": "Sigla Centro",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e0637774-7e97-43b6-a3e5-563ab2f576e2",
        "partitions": [
          {
            "name": "NAV_CENTROS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    NAV_CENTROS1 = BEE{[Name=\"NAV_CENTROS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(NAV_CENTROS1,{{\"SIGLA_CENTRO\", \"Sigla Centro\"}, {\"NOME_CENTRO\", \"Nome Centro\"}, {\"COD_ESTRUTURADO\", \"Código centro\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "56645be1-c13c-46a5-9672-e762c3a9e0d3",
            "sourceColumn": "Column1",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "611794bc-dc79-429c-a42e-e7b76b4fb602",
        "measures": [
          {
            "name": "Vagas ofertadas",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Vagas Oferecidas])",
            "formatString": "0",
            "lineageTag": "722ec88a-7913-47ba-8343-092b9a8546d7"
          },
          {
            "name": "Candidatos inscritos",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Candidatos Inscritos])",
            "formatString": "0",
            "lineageTag": "93ab957e-fccc-43eb-8ac5-ac4ea7b2244b"
          },
          {
            "name": "Candidatos matriculados",
            "expression": "sum(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS[Candidatos Matriculados])",
            "formatString": "0",
            "lineageTag": "9151ce3d-f36c-4b1d-a28e-de71f8d6bde5"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "eaddaaa270234738bef92eb119e0c2d1"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c25614ce-9cfb-44de-af38-bab886d2e0bc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_38ed732a-695c-4c42-86f7-80227cb349ca"
                },
                "isDefault": true,
                "relationship": "467491a2-3f9f-401d-af76-0cc4142a4b25"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fc7776aa-8758-4aa9-a356-94b23a408eb0",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1160af50-9af5-4aea-aec8-e2ed241d0a86",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS (",
                "    CALENDAR(",
                "        min(V_PRPGP_DOCENTES_POS[Data ingresso]), ",
                "        (TODAY())",
                "    ),",
                "    \"Ano\", YEAR ([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_38ed732a-695c-4c42-86f7-80227cb349ca",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "23dbd2c9-80f4-493e-9323-062f8964527d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "83fbf807-da90-4acc-9c2d-ff152cd2a7df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4b79be51-ac80-492e-ace5-a8dfcffc3957",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5910b2f7-b825-40d1-8695-8c51fbd58608",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8e308874-01e5-4808-a875-d9b187df45da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "28bdb175-c6cb-427d-9282-4d231cecd4f8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "dd0a8a3c-78cb-4f7a-88a7-f48253bd3fbc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c7b50b04-9e4e-4f97-a97c-7a8a29c31dc7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6625af6d-d1f9-4bfa-b39d-39b5beb5ac95",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "000090f6-43a6-44c6-9dcf-be085edffc33",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0c57c1ae-50c0-4c68-abd5-ae591759002a",
                "ordinal": 3
              }
            ],
            "lineageTag": "d4034a7f-4437-4525-ab9f-586a2dcb32e6"
          }
        ],
        "isHidden": true,
        "lineageTag": "ebc4751a-8b69-419c-8aab-457fd9355162",
        "partitions": [
          {
            "name": "LocalDateTable_38ed732a-695c-4c42-86f7-80227cb349ca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Data])), 1, 1), Date(Year(MAX('dCalendario'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_519d3b9f-5797-43d5-9959-c15ab834d47a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e84f8e0a-581d-4839-ad3e-8176a4eb2c36",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "af53611f-1606-4aa5-963a-f96ee04841f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8d84eea6-337f-4e4a-8580-aa2e32e1da95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "88555db5-f329-45a8-b0a4-22311a2e8a8d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "92994ccf-dd8e-45f3-874c-fb4a83c17699",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1b0c0bf4-9d0f-4e20-bd86-a2bdc1a1b407",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a6201db3-a62b-491a-a390-2c58f30a89c3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f0b4c6f9-7501-4897-a43a-044dfc3ca079",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "77c64728-7c58-4da4-9c21-5a2c44d29a21",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8228f1bf-8332-4344-a022-dfa794946ffd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6004ad31-0914-420c-b98a-987dd53678d3",
                "ordinal": 3
              }
            ],
            "lineageTag": "635eefbb-3609-4c20-a414-801b25c1e2b7"
          }
        ],
        "isHidden": true,
        "lineageTag": "a2a24232-a305-4bae-9fd6-1dc03909285b",
        "partitions": [
          {
            "name": "LocalDateTable_519d3b9f-5797-43d5-9959-c15ab834d47a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('V_PRPGP_DISCENTES_POS'[Data ingresso])), 1, 1), Date(Year(MAX('V_PRPGP_DISCENTES_POS'[Data ingresso])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_61ca13bd-66ed-497e-a3c1-5b31731daf9b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9673fffe-0735-4c64-a429-eecd8ad461c0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "79e05844-2240-44e4-a788-c7609bc80e81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "96b57732-b218-4e9e-8a1f-67f78847eaf4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d48cef2d-9867-4ce3-ac7d-1943daff7058",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dc94be9f-1377-49db-ac80-8524377c3734",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4f7631cd-897d-4eee-820e-b1286b16ab37",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a37cc09f-6f0b-49ba-b10a-90e2cf29c692",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4879a877-4a3c-459e-bd78-99c3b782b144",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1f8767a6-be27-4535-ba58-5d5b0d9dc522",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ecbf607b-7533-4c87-bae0-f915dad5751e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "aa5aa627-08bb-4d86-8d05-22a9f52d019c",
                "ordinal": 3
              }
            ],
            "lineageTag": "688db96b-a10e-4241-83b4-db1775663ce8"
          }
        ],
        "isHidden": true,
        "lineageTag": "dbd1dba4-94c1-433e-baab-5caa81d116b0",
        "partitions": [
          {
            "name": "LocalDateTable_61ca13bd-66ed-497e-a3c1-5b31731daf9b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('PM_PROJETOS_PARTICIPANTES'[Data fim participação])), 1, 1), Date(Year(MAX('PM_PROJETOS_PARTICIPANTES'[Data fim participação])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_95112233-7078-4557-bc93-37e2b6ea704c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6ee5f2f7-3a9c-43ec-b5a5-530630d75901",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5323a94a-853c-4c1c-970b-82c9d84ac959",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7386789f-6f89-4c90-9775-6e0ae127b808",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "483900bd-3885-4970-9462-ec5c05cf5780",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "238a0c95-bacf-4f1a-a50a-71b997d021f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "adc66a2a-f0b5-4d2e-99d9-359e786caf0f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d44c9b5b-848e-4027-b635-8517a457ed55",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6cbe1d25-7f8e-46dc-9717-7776060db9a8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ed73f11f-a3ce-4d9c-80ea-19d877d68ff7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3f6827cf-cb47-49a2-8adf-b84d591a6cf7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "801a5bee-05b4-43ce-825a-980d056022c3",
                "ordinal": 3
              }
            ],
            "lineageTag": "edde913f-fc57-4794-bceb-322c4cf05f4b"
          }
        ],
        "isHidden": true,
        "lineageTag": "3931fcaa-b649-46f4-b5da-8fa9ce7ea203",
        "partitions": [
          {
            "name": "LocalDateTable_95112233-7078-4557-bc93-37e2b6ea704c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('PM_PROJETOS_PARTICIPANTES'[Data início participação])), 1, 1), Date(Year(MAX('PM_PROJETOS_PARTICIPANTES'[Data início participação])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
        "columns": [
          {
            "name": "ID_CONCURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb579bb5-cab1-4b11-a5d1-aaadd67b355b",
            "sourceColumn": "ID_CONCURSO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CONC_EDICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f3f9f0e7-85ac-423a-a80d-40983e92a6df",
            "sourceColumn": "ID_CONC_EDICAO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_CURSO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "423c4fe3-a457-4ce5-952c-4247c1ac1194",
            "sourceColumn": "ID_CURSO",
            "summarizeBy": "none"
          },
          {
            "name": "Cota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "199f04c7-6a01-4687-bc15-e65ba151d0a6",
            "sourceColumn": "Cota",
            "summarizeBy": "none"
          },
          {
            "name": "Vagas oferecidas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f5da43c-38f6-4fbc-8828-cec5621fbe53",
            "sourceColumn": "Vagas oferecidas",
            "summarizeBy": "none"
          },
          {
            "name": "Candidatos inscritos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc57a0af-4612-4ac1-8d9d-ee24333ada1e",
            "sourceColumn": "Candidatos inscritos",
            "summarizeBy": "none"
          },
          {
            "name": "Candidatos matriculados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eab32f34-7f4d-411e-8194-d6cd0c1773ca",
            "sourceColumn": "Candidatos matriculados",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8bd13327-4213-43e5-962e-92172731b58a",
        "partitions": [
          {
            "name": "V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DB2.Database(\"bi.proj.ufsm.br\", \"bee\", [HierarchicalNavigation=true, Implementation=\"Microsoft\"]),",
                "    BEE = Source{[Schema=\"BEE\"]}[Data],",
                "    V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1 = BEE{[Name=\"V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(V_PRPGP_VAGAS_INSCRITOS_MATRICULADOS1,{\"ANO_CONCURSO\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"DESCR_COTA\", \"Cota\"}, {\"CANDIDATOS_MATRICULADOS\", \"Candidatos matriculados\"}, {\"CANDIDATOS_INSCRITOS\", \"Candidatos inscritos\"}, {\"VAGAS_OFERECIDAS\", \"Vagas oferecidas\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}